//-----------------------------------------------------------------------------| calc_ profil, SCHRAUSSER 2009 - 2011	//
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void _fusszeile();

FILE *tmpStream;

int fn_n=0;
                      
void _profil()
{
	int iLauf;

	printf("\n");
	printf("MAT [v][f] / [i]\n");
	for(iLauf=1; iLauf<=60; iLauf++) cprintf("\xC4"); printf("\n");
	printf("[v] optional Ergebnisvariablenname |z=| \n");
	printf("[f] Formel |1+2, 1+2+(3+4), FN 1, x+ya, 1+FNx+FN(3+ya), ...|\n");
	printf("    Arithmetische Operatoren:\n");
	printf("    |h| n te Potenz von x, xhn\n");
	printf("    |v| n te Wurzel von x, nvx\n");
	printf("    |*| Multipikation, x*y\n");
	printf("    |/| Division, x/y\n");
	printf("    |%%| ModuloDivision, x%%y\n");
	printf("    |+| Addition, x+y\n");
	printf("    |-| Subtraktion, x-y\n");
	printf("[i] Funktionsindexaufruf:\n");
	printf("    |FN|  Funktionsindex, alphabetisch\n");
	printf("    |FNg| Funktionsindex, gruppiert\n");
	printf("    |MAT| MAT_Funktionsindex.pdf\n");
	for(iLauf=1; iLauf<=60; iLauf++) cprintf("\xC4"); printf("\n");
	_fusszeile();
    printf("\xDA\xBF %s @ %s\n", __DATE__, __TIME__);
	exit(1);
};

void _funktionsindex()// alphabetisch 
{
	int iLauf;

	printf("\n");
	printf("MAT FUNKTIONSINDEX\n");
	for(iLauf=1; iLauf<=78; iLauf++) cprintf("\xC4"); printf("\n");
	printf("!!\tDoppelfaktorielle von n, !! n \n"); fn_n++;
	printf("!.!\tTripelfaktorielle von n, !.! n \n"); fn_n++;
	printf("!/FACT\tFaktorielle von n, ! n / FACT n\n"); fn_n++;
	printf("(X)\tAusgabe in Rohwertmatrix X Datei, (X)\n"); fn_n++;
	printf("//\tKommentar, // Kommentar\n"); fn_n++;
	printf(";\t() Binomialkoeffizient n ueber k, ; n,k\n"); fn_n++;
	printf("AAA\tAdditive Wkt ausschl abh: p ein Ereignis, AAA pA1,...,pAn\n"); fn_n++;
	printf("ABS\tAbsolutwert von x, ABS x\n"); fn_n++;
	printf("ACE\tArcuscosecans von x, ACE x\n"); fn_n++;
	printf("ACS\tArcuscosinus von x, ACS x\n"); fn_n++;
	printf("ACT\tArcuscotangens von x, ACT x\n"); fn_n++;
	printf("AEA\tAdditive Wkt einschl abh: p ein oder beide E, AEA pA, pB, pAB\n"); fn_n++;
	printf("AEU\tAdditive Wkt einschl unabh: p mindestens ein E, AEU pA1,...,pAn\n"); fn_n++;
	printf("AGAM\tInvers Alpha-Gamma von Gamma, AGAM g\n"); fn_n++;
	printf("AHC\tHyperbolischer Arcuscosinus von x, AHC x\n"); fn_n++;
	printf("AHG\tHyperbolischer Arcuscotangens von x, AHG x\n"); fn_n++;
	printf("AHN\tHyperbolischer Arcussecans von x, AHN x\n"); fn_n++;
	printf("AHO\tHyperbolischer Arcuscosecans von x, AHO x\n"); fn_n++;
	printf("AHS\tHyperbolischer Arcussinus von x, AHS x\n"); fn_n++;
	printf("AHT\tHyperbolischer Arcustangens von x, AHT x\n"); fn_n++;
	printf("AM_\tArithmetisches Mittel von Vektor x, AM_ x1,x2,...,xn\n"); fn_n++;
	printf("AMG\tGewichtetes Arithmetisches Mittel von Vektor x, AMG x1,n1,...,xk,nk\n"); fn_n++;
	printf("AMX\tArithmetisches Mittel zu xy von Matrix X, AMX x1,y1,...,xn,yn\n"); fn_n++;
	printf("ANI\tAlpha Niveau p, ANI x,m0,sm,df \n"); fn_n++;
	printf("APW\tA-Wert zur Wahrscheinlichkeit p bei a und b, APW p,a,b\n"); fn_n++;
	printf("APX\tKurvenanpassungsprozeduren, APX\n"); fn_n++;
	printf("ASE\tArcussecans von x, ASE x\n"); fn_n++;
	printf("ASN\tArcussinus von x, ASN x\n"); fn_n++;
	printf("ATN\tArcustangens von x, ATN x\n"); fn_n++;
	printf("AWN\tAdditive Wkt: A mindestens 1 mal bei n, AWN pA,n\n"); fn_n++;
	printf("AXY\tRegressionskoeffizient axy, F(y)=x=bxy*y+axy, AXY x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("AYX\tRegressionskoeffizient ayx, F(x)=y=byx*x+ayx, AYX x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("BGAM\tInvers Beta-Gamma von Gamma, BGAM g\n"); fn_n++;
	printf("BMK\tBetagewicht b zu Rc,12...k, BMK i,k,r1c,r2c,...,rkc,r12,...,r1k,...,rik\n"); fn_n++;
	printf("BN0\tBinomial Test; Binomial Punkt-Wkt. P0, BN0 b,c\n"); fn_n++;
	printf("BN1\tBinomial Test; Exakt 1-seitiges Niveau pexact1, BN1 b,c\n"); fn_n++;
	printf("BN2\tBinomial Test; Exakt 2-seitiges Niveau pexact2, BN2 b,c\n"); fn_n++;
	printf("BNI\tBeta Niveau p, BNI x,m1,sm,df \n"); fn_n++;
	printf("BNM\tMittelwert zur Binomialverteilung, BNM p,n\n"); fn_n++;
	printf("BNP\tBinomial Punkt-Wahrscheinlichkeit, p genau k mal von n, BNP p,k,n\n"); fn_n++;
	printf("BNS\tStreuung zur Binomialverteilung, BNS p,n\n"); fn_n++;
	printf("BNW\tBinomial Wahrscheinlichkeit, p hoechstens (<=) k mal von n, BNW p,k,n\n"); fn_n++;
	printf("BSK\tBiserale Korrelation rbis zur Korrelation rpb bei n1, n2, BSK r,n1,n2\n"); fn_n++;
	printf("BSM\tBinomialsimulationen, BSM\n"); fn_n++;
	printf("BWA\tBedingte Wkt: B unter der Bedingung von A, BWA pA,pAB \n"); fn_n++;
	printf("BXY\tRegressionskoeffizient bxy, F(y)=x=bxy*y+axy, BXY x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("BYS\tBayes Formulierung, BYS pA1,pB|A1,...,pAn,pB|An\n"); fn_n++;
	printf("BYX\tRegressionskoeffizient byx, F(x)=y=byx*x+ayx, BYX x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("CHF\tKombinationen zum 2^k-Felder Test (2x2 fix), CHF z1,...,z2k \n"); fn_n++;
	printf("CHG\tKombinationen zum 2^k-Felder Test, CHG z1,...,z2k \n"); fn_n++;
	printf("CI_\tHalber Vertrauensbereich ci zu P CI bei sm und df, CI_ P,sm,df\n"); fn_n++;
	printf("CKL\tKombinationen zum kxl-Felder Test, CKL k,l,z11,...,z1S,...,zZ1,...,zZS\n"); fn_n++;
	printf("COS\tCosinus von x, COS x\n"); fn_n++;
	printf("COT\tCotangens von x, COT x\n"); fn_n++;
	printf("COV\tKovarianz s2xy von x und y zur Matrix X, COV x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("COX\tKovarianz s2xy aus x, y und xy, COX x,y,xy \n"); fn_n++;
	printf("CPW\tX-Wert zur Wahrscheinlichkeit p bei a und b, CPW p,a,b\n"); fn_n++;
	printf("CQT\tCochran Q-Test, CQT nT,T1,...,Tm,L1,...,Ln\n"); fn_n++;
	printf("CSE\tCosecans von x, CSE x\n"); fn_n++;
	printf("CUB\t3. Potenz von x, CUB x\n"); fn_n++;
	printf("CUR\t3. Wurzel von x, CUR x\n"); fn_n++;
	printf("CW_\tC-Norm Wert zu z-Wert, CW_ z\n"); fn_n++;
	printf("D__\tSchrausser's d von Vektor x, D__ x1,x2,...,xn\n"); fn_n++;
	printf("DAT\tAusgabedatei, DAT\n"); fn_n++;
	printf("DATR\tReportdatei, DATR\n"); fn_n++;
	printf("DATX\tRohwertmatrix X Datei, DATX\n"); fn_n++;
	printf("DAW\tDichte d bei a und b zu A-Wert, DAW A,a,b\n"); fn_n++;
	printf("DCW\tDichte d bei a und b zu X-Wert, DCW X,a,b\n"); fn_n++;
	printf("DEG\tWinkel a von Bogenmass rad, DEG rad\n"); fn_n++;
	printf("DET\tDeterminationskoeffizient der Vektoren x und y, DET x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("DFW\tDichte d bei df1 und df2 zu F-Wert, DFW F,df1,df2\n"); fn_n++;
	printf("DGAM\tGamma Verteilungs-Dichte zu x bei c, DGAM x,c\n"); fn_n++;
	printf("DGM\tGamma Dichte bei x und t, DGM x, t\n"); fn_n++;
	printf("DGR\tGrad x von Neugrad xg, DGR xg\n"); fn_n++;
	printf("DLW\tDichte d bei a und b zu L-Wert, DLW L,a,b\n"); fn_n++;
	printf("DTW\tDichte d bei df zu t-Wert, DTW t,df\n"); fn_n++;
	printf("DVARO\tVarianzoberflaeche von Vektor x, DVARO x1,x2,...,xn\n"); fn_n++;
	printf("DVW\tDichte d bei a und b zu V-Wert, DVW V,a,b\n"); fn_n++;
	printf("DWW\tDichte d bei a und b zu W-Wert, DWW W,a,b\n"); fn_n++;
	printf("DXW\tDichte d bei df zu x2-Wert, DXW x,df\n"); fn_n++;
	printf("DZW\tDichte d zu z-Wert, DZW z\n"); fn_n++;
	printf("EDX\tEindimensionales x2, EDX h1,h2,...,hn\n"); fn_n++;
	printf("EFG\tEffektgroesse e, EFG m0,m1,sg\n"); fn_n++;
	printf("EFS\tEffektstaerke ep, EFS p,n,df\n"); fn_n++;
	printf("EUL\tEulersche Konstante, EUL\n"); fn_n++;
	printf("EXP\tEulersche Grenzwertformulierung von e zur Basis n, EXP n (0: n=1e+11)\n"); fn_n++;
	printf("EXZ\t4. Potenzmoment zu Vektor x, EXZ x1,x2,...,xn\n"); fn_n++;
	printf("EZP\t4. Potenzmoment zu Vektor x (Pop.), EZP x1,x2,...,xn\n"); fn_n++;
	printf("FMK\tF-Wert zu R bei gegebenem n und k, FMK R,n,k\n"); fn_n++;
	printf("FMP\tF-Wert zu Rc,A.B u. Rc,(A.B) mit n, kA, pB, FMP RcAB, RcB, n,k,p \n"); fn_n++;
	printf("FN1...\tTemporaergerueste zur Funktionsentwicklung, FN1 0,0\n"); fn_n++;
	printf("FORM\tVorkommastellen, Stellen, Zahlenformat, FORM v,s,z; z(1=f,2=g,3=G)\n"); fn_n++;
	printf("FPW\tF-Wert zur Wahrscheinlichkeit p bei df1 und df2, FPW p,df1,df2\n"); fn_n++;
	printf("FX0\tFisher Exact Test; Hypergeometrische Punkt-Wkt. P0, FX0 a,b,c,d\n"); fn_n++;
	printf("FX1\tFisher Exact Test; Exakt 1-seitiges Niveau pexact1, FX1 a,b,c,d\n"); fn_n++;
	printf("FX2\tFisher Exact Test; Exakt 2-seitiges Niveau pexact2, FX2 a,b,c,d\n"); fn_n++;
	printf("FZR\tFishers Z zum Korrelationskoeffizienten r, FZR r\n"); fn_n++;
	printf("GAMMA\tGamma von x, GAMMA x\n"); fn_n++;
	printf("GFZ\tGemitteltes Fisher Z, GFZ Z1, nr1,..., Zk,nrk\n"); fn_n++;
	printf("GM_\tGeometrisches Mittel von Vektor x, GM_ x1,x2,...,xn\n"); fn_n++;
	printf("GMP\tGeometrische Punkt-Wkt., pA das 1-te mal bei r+1, GMP p,r+1\n"); fn_n++;
	printf("GMW\tGeometrische Wkt., pA das 1-te mal bis (<=) r+1, GMW p,r+1\n"); fn_n++;
	printf("GRAD\tNeugrad xg von Grad x, GRAD x\n"); fn_n++;
	printf("GSD\ts zur geschaetzten Populations-Stdabw s' bei n, GSD sg,n\n"); fn_n++;
	printf("GSM\ts zum geschaetzten Stdfehler des AM bei n, GSM smg,n\n"); fn_n++;
	printf("GVA\ts zur geschaetzten Populations-Varianz bei n, GVA s2g,n\n"); fn_n++;
	printf("HCE\tHyperbolischer Cosecans von x, HCE x\n"); fn_n++;
	printf("HCS\tHyperbolischer Cosinus von x, HCN x\n"); fn_n++;
	printf("HCT\tHyperbolischer Cotangens von x, HCT x\n"); fn_n++;
	printf("HF0\t2^k Test (2x2 fix); Hypergeometrische Punkt-Wkt, HF0 z1,...,z2k \n"); fn_n++;
	printf("HF2\t2^k Test (2x2 fix); Exakt 2-seitiges Niveau pexact2, HF2 z1,...,z2k \n"); fn_n++;
	printf("HG0\t2^k Test; Hypergeometrische Punkt-Wkt, HG0 z1,...,z2k \n"); fn_n++;
	printf("HG2\t2^k Test; Exakt 2-seitiges Niveau pexact2, HG2 z1,...,z2k \n"); fn_n++;
	printf("HGM\tMittelwert zur hypergeometrischen Verteilung, HGM n,N,K\n"); fn_n++;
	printf("HGP\tHypergeometrische Punkt-Wkt., kA von n von N mit KA, HGP k,n,N,K\n"); fn_n++;
	printf("HGS\tStreuung zur hypergeometrischen Verteilung, HGS n,N,K\n"); fn_n++;
	printf("HGW\tHypergeometrische Wkt., <= kA von n von N mit KA, HGW k,n,N,K\n"); fn_n++;
	printf("HM_\tHarmonisches Mittel von Vektor x, HM_ x1,x2,...,xn\n"); fn_n++;
	printf("HSE\tHyperbolischer Secans von x, HSE x\n"); fn_n++;
	printf("HSM\tHypergeometrische Simulationen, HSM\n"); fn_n++;
	printf("HSN\tHyperbolischer Sinus von x, HSN x\n"); fn_n++;
	printf("HTN\tHyperbolischer Tangens von x, HTN x\n"); fn_n++;
	printf("IACE\tArcuscosecans von x iterativ, IACE x\n"); fn_n++;
	printf("IACT\tArcuscotangens von x iterativ, IACT x\n"); fn_n++;
	printf("IAHC\tHyperbolischer Arcuscosinus von x iterativ, IAHC x\n"); fn_n++;
	printf("IAHG\tHyperbolischer Arcuscotangens von x iterativ, IAHG x\n"); fn_n++;
	printf("IAHN\tHyperbolischer Arcussecans von x iterativ, IAHN x\n"); fn_n++;
	printf("IAHO\tHyperbolischer Arcuscosecans von x iterativ, IAHO x\n"); fn_n++;
	printf("IAHS\tHyperbolischer Arcussinus von x iterativ, IAHS x\n"); fn_n++;
	printf("IAHT\tHyperbolischer Arcustangens von x iterativ, IAHT x\n"); fn_n++;
	printf("IASE\tArcussecans von x iterativ, IASE x\n"); fn_n++;
	printf("IGM\tGamma Integrale zu x bei d, IGM x, d\n"); fn_n++;
	printf("IMB\tTeststaerke 1-Beta, IMB x,m1,sm,df\n"); fn_n++;
	printf("INT\tGanze Zahl von x abgerundet, INT x\n"); fn_n++;
	printf("INTA\tGanze Zahl von x aufgerundet, INTA x\n"); fn_n++;
	printf("INTR\tGanze Zahl von x gerundet, INTR x\n"); fn_n++;
	printf("IQ_\tIQ-Norm Wert zu z-Wert, IQ_ z\n"); fn_n++;
	printf("IQK\tIQ-Norm Wert fuer Kinder zu z-Wert, IQK z\n"); fn_n++;
	printf("K_M\tKombinationsmatrix von Vektor x ohne Wh zu m, K_M m, x1,...xn\n"); fn_n++;
	printf("KBR\tBiserale Rangkorrelation rbisR, KBR x1,g1,...,xn,gn; g(1,2)\n"); fn_n++;
	printf("KBS\tBiserale Korrelation rbis, KBS x1,g1,...,xn,gn; g(1,2)\n"); fn_n++;
	printf("KFA\t2^k-Felder x2, KFA z11,...,z2^k\n"); fn_n++;
	printf("KL0\tkxl Test; Hypergeom. Punkt-Wkt, KL0 Z,S,z11,..,z1S,..,zZ1,..,zZS\n"); fn_n++;
	printf("KL2\tkxl Test; Exakt 2-seitiges Niv pexact2, KL2 Z,S,z11,.,z1S,.,zZ1,.,zZS\n"); fn_n++;
	printf("KLX\tkxl-Felder x2, KL2 Z,S,z11,..,z1S,..,zZ1,..,zZS\n"); fn_n++;
	printf("KMW\tKombination von n mit Wiederholung zu m, KMW n,m\n"); fn_n++;
	printf("KOR\tKorrelationskoeffizient rxy zur Matrix X, KOR x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("KOX\tKorrelationskoeffizient rxy aus x,y,x2,y2,xy, KOX x,y,x2,y2,xy\n"); fn_n++;
	printf("KPB\tPunktbiserale Korrelation rpb, KPB x1,g1,...,xn,gn; g(1,2)\n"); fn_n++;
	printf("KPH\tPhi Korrelation, KPH a,b,c,d\n"); fn_n++;
	printf("KPM\tPhi Korrelation maximal, KPM a,b,c,d\n"); fn_n++;
	printf("KRP\tPartial-Korrelationskoeff. rxy.B zu pa2 bei n, k (Z-Vtlg.), KRP pa2,n,k\n"); fn_n++;
	printf("KRS\tRangkorrelation rs zur Matrix X, KRS x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("KTET\tTetrachorische Korrelation rtet, KTET a,b,c,d\n"); fn_n++;
	printf("KWM\tKombinationsmatrix von Vektor x mit Wh zu m, KWM m, x1,...xn\n"); fn_n++;
	printf("LGX\tLogarithmus zur Basis a von x, LGX a,x\n"); fn_n++;
	printf("LN\tLogarithmus zur Basis e von x, LN x\n"); fn_n++;
	printf("LOG\tDekadischer Logarithmus von x, LOG x\n"); fn_n++;
	printf("LPW\tL-Wert zur Wahrscheinlichkeit p bei a und b, LPW p,a,b\n"); fn_n++;
	printf("LTO\tLotto Simulation1, LTO k,N,z1,...,z6\n"); fn_n++;
	printf("LTO\tLotto Simulation2, LTO N,M,z1,...,z6\n"); fn_n++;
	printf("MAC\tMultipler Regressionskoeff. ac,12...k, MAC xc,sc,b1,x1,s1,...,bk,xk,sk\n"); fn_n++;
	printf("MAX\tMaximalwert von Vektor x, MAX x1,x2,...,xn\n"); fn_n++;
	printf("MBC\tRohwertgewicht bc, MBC sc,bi,si\n"); fn_n++;
	printf("MD_\tMedian von Vektor x, MD_ x1,x2,...,xn\n"); fn_n++;
	printf("MDT\tDeterminante detA von Matrix A, MDT n,a11,...,a1n,...,ann\n"); fn_n++;
	printf("MIN\tMinimalwert von Vektor x, MIN x1,x2,...,xn\n"); fn_n++;
	printf("MKP\tMultipler-Korrelationskoeffizient R zu Niveau pa2 bei n, k, MKP pa2,n,k\n"); fn_n++;
	printf("MKR\tMultipler-Korrelationskoeffizient Rc,12, MKR r1c,r2c,r12\n"); fn_n++;
	printf("MKRN\tMultipler-Korrelationskoeff. Rc,12...k, MKRN b1,b2,..,bk,r1c,r2c,..,rkc\n"); fn_n++;
	printf("MN0\tk-Felder; Multinomiale Punkt-Wkt, MN0 z1,...,zk\n"); fn_n++;
	printf("MN2\tk-Felder; Exakt 2-seitiges Niveau pexact2, MN2 z1,...,zk\n"); fn_n++;
	printf("MNP\tMultinomial Punkt-Wahrscheinlichkeit, MNP p1,k1,...,ps,ks,n\n"); fn_n++;
	printf("MNX\tMcNemar x2, MNX b,c\n"); fn_n++;
	printf("MNYX\tMcNemar x2 kontinuitaetskorrigiert, MNYX b,c\n"); fn_n++;
	printf("MPW\tMultiplikative Wkt unabh: p alle Ereignisse, MPW pA1,...,pAn\n"); fn_n++;
	printf("MPW\tMultiplikative Wkt abh: p alle Ereignisse, MPW pA1,pA2|A1,..,pAn|A1..n\n"); fn_n++;
	printf("MR_\tRangmittel von Vektor x, MR_ x1,x2,...,xn\n"); fn_n++;
	printf("MRI\tMatrizen-Inversions Element rii zu R-1, MRI i,k,r12,...,r1k,...,rik\n"); fn_n++;
	printf("MSP\tSpur spA einer quadratischen Matrix A, MSP n,a11,...,a1n,...,ann\n"); fn_n++;
	printf("MUTS\tU-Test; Populationswert mU, MUTS x1,g1,...,xn,gn; g(1,2)\n"); fn_n++;
	printf("MWTS\tWilcoxon-Test; Populationswert mT, MWTS x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("MXA\tMatr.-Additions Element cij, MXA i,j,n,a11,.,a1k,.,ank,b11,.,b1k,.,bnk\n"); fn_n++;
	printf("MXI\tMatrizen-Inversions Element aij, MXI i,j,n,a11,...,a1n,...,ann\n"); fn_n++;
	printf("MXM\tMatr.-Multipl Elmt cij, MXM i,j,n1,k1,a11,.,a1k,.,ank,b11,.,b1m,.,bkm\n"); fn_n++;
	printf("MXQ\tMatr.-Quadrierungs Elmt cij, MXA i,j,n1,k1,a11,.,a1k,.,ank\n"); fn_n++;
	printf("MXS\tMatr.-Subtraktions Elmt xij, MXS i,j,n,b11,.,b1k,.,bnk,a11,.,a1k,.,ank\n"); fn_n++;
	printf("MXT\tMatrizen-Transponierungs Element aij, MXT i,j,n,a11,...,a1k,...,ank\n"); fn_n++;
	printf("MXV\tMatrizen-Verkettungs Element b/cij, MXV i,j,n,a11,...,a1n,...,ann\n"); fn_n++;
	printf("N__\tWerteumfang n von Vektor x, N__ x1,x2,...,xn\n"); fn_n++;
	printf("NBP\tNegative Binomial Punkt Wkt., p das k-te mal bei r+k, NBP p,k,r+k\n"); fn_n++;
	printf("NBW\tNegative Binomial Wkt., p hoechstens das k-te mal bei r+k, NBN p,k,r+k\n"); fn_n++;
	printf("NCR/KM_\tKombination von n ohne Wiederholung zu m, NCR n,m / KM_ n,m\n"); fn_n++;
	printf("NPR/VR_\tVariation von n ohne Wiederholung zu m, NPR n,m / VR_ n,m\n"); fn_n++;
	printf("ONZ\tOptimaler Stichprobenumfang nopt (z-Vtlg.), ONZ p,e\n"); fn_n++;
	printf("OPN\tOptimaler Stichprobenumfang nopt, OPN p,e,df\n"); fn_n++;
	printf("OPP\tOptimales Alpha Niveau popt, OPP, e,n,df\n"); fn_n++;
	printf("P_M\tPermutationsmatrix von Vektor x zu 1 Klasse, P_M x1,...xn\n"); fn_n++;
	printf("P2M\tPermutationsmatrix von Vektor x zu 2 Klassen, P2M k1,k2,x1,...xn\n"); fn_n++;
	printf("PAW\tWahrscheinlichkeit p bei a und b zu A-Wert, PAW A,a,b\n"); fn_n++;
	printf("PCW\tWahrscheinlichkeit p bei a und b zu X-Wert, PCW X,a,b\n"); fn_n++;
	printf("PFD\tWahrscheinlichkeit p bei df12 zu F-Wert (Dichteintegral), PFD F,df1,df2\n"); fn_n++;
	printf("PFW\tWahrscheinlichkeit p bei df1 und df2 zu F-Wert, PFW f,df1,df2\n"); fn_n++;
	printf("PI_\tKreiskonstante, PI_\n"); fn_n++;
	printf("PKR\tPartial-Korrelationskoeffizient rxy.z, PKR rxy,rxz,ryz\n"); fn_n++;
	printf("PKRB\tPartial-Korrelationskoeffizient rxy.B, PKRB RyxB,RyB\n"); fn_n++;
	printf("PKRB\tMultipler Partial- Rc,A.B, PKRB RcAB,RcB\n"); fn_n++;
	printf("PKS\tSemipartial-Korrelationskoeffizient ry(x.z), rx(y.z), PKS rxy,rxz,ryz\n"); fn_n++;
	printf("PKSB\tSemipartial-Korrelationskoeffizient ry(x.B), rx(y.B), PKSB RyxB,RyB \n"); fn_n++;
	printf("PKSB\tMultipler Semipartial-Rc,(A.B), PKSB RcAB,RcB \n"); fn_n++;
	printf("PLW\tWahrscheinlichkeit p bei a und b zu L-Wert, PLW L,a,b\n"); fn_n++;
	printf("PM_\tPermutation von n ohne Klassen, PM_ n\n"); fn_n++;
	printf("PMM\tPermutationsmatrix von Vektor x zu m Klassen, PMM k1,...,km,x1,...xn\n"); fn_n++;
	printf("PMW\tPermutation von n zu den Klassen k1,k2,...kl, PMW n,k1,k2,...,kl\n"); fn_n++;
	printf("PNP\tPoisson Punkt-Wahrscheinlichkeit, p genau k mal von n, PNP p,k,n\n"); fn_n++;
	printf("PNW\tPoisson Wahrscheinlichkeit, p hoechstens (<=) k mal von n, PNW p,k,n\n"); fn_n++;
	printf("PR_\tProzentrang PR zu z-Wert, PR_ z\n"); fn_n++;
	printf("PSUM\tProduktsumme von Vektor x, PSUM x1,x2,...,xn\n"); fn_n++;
	printf("PTD\tWahrscheinlichkeit p bei df zu t-Wert (Dichteintegral), PTD t,df\n"); fn_n++;
	printf("PTW\tWahrscheinlichkeit p bei df zu t-Wert, PTW t,df\n"); fn_n++;
	printf("PVW\tWahrscheinlichkeit p bei a und b zu V-Wert, PVW V,a,b\n"); fn_n++;
	printf("PWW\tWahrscheinlichkeit p bei a und b zu W-Wert, PWW W,a,b\n"); fn_n++;
	printf("PXD\tWahrscheinlichkeit p bei df zu x2-Wert (Dichteintegral), PXD x,df\n"); fn_n++;
	printf("PXW\tWahrscheinlichkeit p bei df zu x2-Wert, PXW x,df\n"); fn_n++;
	printf("PZD\tWahrscheinlichkeit p zu z-Wert (Dichteintegral), PZD z\n"); fn_n++;
	printf("PZW\tWahrscheinlichkeit p zu z-Wert, PZW z\n"); fn_n++;
	printf("QSUM\tSumme aller x2 von Vektor x, QSUM x1,x2,...,xn\n"); fn_n++;
	printf("R//\tKommetar in Reportdatei, R// Kommentar\n"); fn_n++;
	printf("RAD\tBogenmass rad von Winkel a, RAD a\n"); fn_n++;
	printf("RCP\tReziprokwert von x, 1/x, RCP x\n"); fn_n++;
	printf("RDA\tQuerdifferenz von x, RDA x\n"); fn_n++;
	printf("RDN\tReduktion von x, RDN x\n"); fn_n++;
	printf("RED\tRedundanz von y, Red(yx), RED x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("REP\tAusgabe in Reportdatei, REP\n"); fn_n++;
	printf("REST\tRest von x, REST x\n"); fn_n++;
	printf("RFZ\tKorrelationskoeffizient r zu Fishers Z, RFZ Z\n"); fn_n++;
	printf("RLT\tRoulettesimulationen, RLT\n"); fn_n++;
	printf("RNB\tZufallsmatrix N nach bivariater Verteilung , RNB\n"); fn_n++;
	printf("RND\tQuasizufallszahl (Anfangswert a) in den Grenzen x,y, RND a,x,y\n"); fn_n++;
	printf("RNG\tWertebereich von Vektor x, RNG x1,x2,...,xn\n"); fn_n++;
	printf("RNN\tZufallsvektor n nach Verteilung F(n), RNN\n"); fn_n++;
	printf("RNV\tQuasizufalls-Vektorelement px1 (Anfangswert a), RNV a,x1,...xn\n"); fn_n++;
	printf("RPT\tKorrelationskoeffizient r zu Niveau pa2  bei n (t-Vtlg.), RPT pa2,n\n"); fn_n++;
	printf("RPZ\tKorrelationskoeffizient r zu Niveau pa2  bei n (Z-Vtlg.), RPZ pa2,n\n"); fn_n++;
	printf("RSUM\tRangsumme von Vektor x, RSUM x1,x2,...,xn\n"); fn_n++;
	printf("RYX\tRegressionskoeffizient ryx zur Matrix X, RYX x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("S__\tStanine-Norm Wert S zu z-Wert, S__ z\n"); fn_n++;
	printf("SBS\tStandardfehler srbis zur rbis, SBS x1,g1,...,xn,gn; g(1,2)\n"); fn_n++;
	printf("SCH\t3. Potenzmoment zu Vektor x, SCH x1,x2,...,xn\n"); fn_n++;
	printf("SD_\tStandardabweichung von Vektor x, SD_ x1,x2,...,xn\n"); fn_n++;
	printf("SDG\tGeschaetzte Populations-Stdabw von Vektor x, SDG x1,x2,...,xn\n"); fn_n++;
	printf("SDV\tVariationsquotient v von Vektor x, SDV x1,x2,...,xn, \n"); fn_n++;
	printf("SDX\tGeschaetzte Populations-Stdabw von s bei n, SDX s,n\n"); fn_n++;
	printf("SEC\tSecans von x, SEC x\n"); fn_n++;
	printf("SEX\tStandardfehler des 4. Potenzmoments bei n, SEX n\n"); fn_n++;
	printf("SFZ\tStandardabweichung zu Fishers Z bei n, SFZ n\n"); fn_n++;
	printf("SGN\tVorzeichen von x, SGN x (-1,0,1)\n"); fn_n++;
	printf("SHP\t3. Potenzmoment zu Vektor x (Pop.), SHP x1,x2,...,xn\n"); fn_n++;
	printf("SIG\t2-seitiges Signifikanzniveau zu z- oder t-Wert bei p, SIG p\n"); fn_n++;
	printf("SIN\tSinus von x, SIN x\n"); fn_n++;
	printf("SKM\tSchrumpfungskorrektur zu R bei gegebenem n und k, SKM R,n,k\n"); fn_n++;
	printf("SMG\tGeschaetzter Stdfehler des AM zu Vektor x, SMG x1,x2,...,xn\n"); fn_n++;
	printf("SMX\tGeschaetzter Stdfehler des AM zu Vektor x aus s und n, SMX s,n\n"); fn_n++;
	printf("SN_\tStandardnotenwert N zu z-Wert, SN_ z\n"); fn_n++;
	printf("SQR\tQuadratwurzel von x, SQR x\n"); fn_n++;
	printf("SQU\tQuadrat von x, SQU x\n"); fn_n++;
	printf("SSH\tStandardfehler des 3. Potenzmoments bei n, SSH n\n"); fn_n++;
	printf("STET\tStandardfehler stet zur Tetrachorische Korrelation rtet, STET a,b,c,d\n"); fn_n++;
	printf("STN\tSten-Norm Wert zu z-Wert, STN z\n"); fn_n++;
	printf("SUM\tSumme von Vektor x, SUM x1,x2,...,xn\n"); fn_n++;
	printf("SUTS\tU-Test; Standardfehler sU, SUTS x1,g1,...,xn,gn; g(1,2)\n"); fn_n++;
	printf("SW_\tStandardnormwert Z zu z-Wert, SW_ z\n"); fn_n++;
	printf("SWTS\tWilcoxon-Test; Standardfehler sT, SWTS x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("SWX\tSchwellenwert xcrit, SWX m0,m1,sg,n\n"); fn_n++;
	printf("T__\tT-Norm Wert zu z-Wert bei Normalverteilung, T__ z\n"); fn_n++;
	printf("T1B\tBinomiales Niveau pexact1 bei p, T1B p,kmin,kmax,nmin,nmax \n"); fn_n++;
	printf("T1F\t1-stgs. Niveau zw. min_F und max_F, T1F min_F,max_F,st,df1,df2\n"); fn_n++;
	printf("T1H\tHypergmtr. Niveau pexact1 bei K,N, T1H K,N,kmin,kmax,nmin,nmax \n"); fn_n++;
	printf("T1K\t1-seitiges Niveau pa1 zur Korrelation r, T1K rmin,rmax,nmin,nmax,st\n"); fn_n++;
	printf("T1T\t1-stgs. Niveau zw. min_t und max_t in st bei df, T1T min_t,max_t,st,df\n"); fn_n++;
	printf("T1X\t1-stgs. Niveau zw. min_x und max_x in st bei df, T1X min_x,max_x,st,df\n"); fn_n++;
	printf("T1Z\t1-stgs. Niveau zu z-Wert zw. min_z und max_z in st , T1Z min_z,max_z,st\n"); fn_n++;
	printf("T2B\tBinomiales Niveau pexact2 bei p, T2B p,kmin,kmax,nmin,nmax \n"); fn_n++;
	printf("T2F\t2-stgs. Niveau zw. min_F und max_F, T2F min_F,max_F,st,df1,df2\n"); fn_n++;
	printf("T2H\tHypergmtr. Niveau pexact2 bei K,N, T2H K,N,kmin,kmax,nmin,nmax \n"); fn_n++;
	printf("T2K\t2-seitiges Niveau pa2 zur Korrelation r, T2K rmin,rmax,nmin,nmax,st\n"); fn_n++;
	printf("T2T\t2-stgs. Niveau zw. min_t und max_t in st bei df, T2T min_t,max_t,st,df\n"); fn_n++;
	printf("T2X\t2-stgs. Niveau zw. min_x und max_x in st bei df, T2X min_x,max_x,st,df\n"); fn_n++;
	printf("T2Z\t2-stgs. Niveau zu z-Wert zw. min_z und max_z in st , T2Z min_z,max_z,st\n"); fn_n++;
	printf("TAN\tTangens von x, TAN x\n"); fn_n++;
	printf("TBB\tBinomiale Punkt-Wkt. P0 bei p, TBB p,kmin,kmax,nmin,nmax \n"); fn_n++;
	printf("TBF\tF-Wert zw. min_F und max_F in st Stufen, TBF min_F,max_F,st\n"); fn_n++;
	printf("TBH\tHypergmtr. Punkt-Wkt. P0 bei K,N, TBH K,N,kmin,kmax,nmin,nmax \n"); fn_n++;
	printf("TBM\tt-Wert zu bi, Element rii von R-1 zu R bei n, k, TBM bi,rii,R,n,k\n"); fn_n++;
	printf("TBR\tn Quasizufallszahlen (Anfangsw.=a) in den Grenzen x,y, TBR a,x,y,n\n"); fn_n++;
	printf("TBT\tt-Wert zw. min_t und max_t in st Stufen, TBT min_t,max_t,st\n"); fn_n++;
	printf("TBX\tx2-Wert zw. min_x und max_x in st Stufen, TBX min_x,max_x,st\n"); fn_n++;
	printf("TBZ\tz-Wert zw. min_z und max_z in st Stufen, TBZ min_z,max_z,st\n"); fn_n++;
	printf("TCH\tKombinationen 2x2C bei K,N, TCH K,N,kmin,kmax,nmin,nmax \n"); fn_n++;
	printf("TDF\tDichte d zw. min_F und max_F, TDF min_F,max_F,st,df1,df2\n"); fn_n++;
	printf("TDT\tDichte d zw. min_t und max_t in st bei df, TDT min_t,max_t,st,df\n"); fn_n++;
	printf("TDX\tDichte d zw. min_x und max_x in st bei df, TDX min_x,max_x,st,df\n"); fn_n++;
	printf("TDZ\tDichte d zu z-Wert zw. min_z und max_z in st , TDZ min_z,max_z,st\n"); fn_n++;
	printf("TEE\teopt zw. min/max_pa2 in st bei min/max_n, TEE m_pa2,mx_pa2,st,m_n,mx_n\n"); fn_n++;
	printf("TFS\tF-Wert zum Niveau pa2 bei df1,2, TFS pa2,mn_df1,mx_df1,mn_df2,mx_df2\n"); fn_n++;
	printf("TKV\tt-Wert zur Varianzdiff. korr. Vektoren x und y, TKV x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("TMS\tR zw. min/max_pa2 bei min/max_n und k, TMS m_p, mx_p,st,m_n,mx_n,k\n"); fn_n++;
	printf("TNE\tnopt zw. min/max_e in st bei min/max_pa2, TNE m_e,mx_e,st,m_pa2,mx_pa2\n"); fn_n++;
	printf("TPE\tpopt zw. min/max_e in st bei min/max_n, TPE m_e,mx_e,st,m_n,mx_n\n"); fn_n++;
	printf("TPF\tProzentrang p zw. min_F und max_F, TPF min_F,max_F,st,df1,df2\n"); fn_n++;
	printf("TPK\tProzentrang p zur Korrelation r, TPK rmin,rmax,nmin,nmax,st\n"); fn_n++;
	printf("TPS\trxy.B zw. min/max_pa2 bei min/max_n und k, TPS m_p, mx_p,st,m_n,mx_n,k\n"); fn_n++;
	printf("TPT\tProzentrang p zw. min_t und max_t in st bei df , TPT min_t,max_t,st,df\n"); fn_n++;
	printf("TPW\tt-Wert zur Wahrscheinlichkeit p bei df, TPW p,df\n"); fn_n++;
	printf("TPX\tProzentrang p zw. min_x und max_x in st bei df , TPX min_x,max_x,st,df\n"); fn_n++;
	printf("TPZ\tProzentrang p zu z-Wert zw. min_z und max_z in st , TPZ min_z,max_z,st\n"); fn_n++;
	printf("TRS\tr zw. min/max_pa2 bei min/max_n (t-Vtlg.), TRS m_p, mx_p,st,m_n,mx_n\n"); fn_n++;
	printf("TRW\tt-Wert zur Korrelation r bei n, TRW r,n\n"); fn_n++;
	printf("TT_\tt-Wert fuer 1 Gruppe bei x, s und n zur Pruefgroesse y, TT_ x,s,n,y\n"); fn_n++;
	printf("TTS\tt-Wert zum Niveau pa2 bei df, TTS min_pa2,max_pa2,st, min_df,max_df\n"); fn_n++;
	printf("TU_\tt-Wert zu 2 unverbundenen Gruppen, TU_ x1,g1,...,xn,gn; g(1,2)\n"); fn_n++;
	printf("TUX\tt-Wert zu 2 unverbundenen Gruppen, TUX x1,s1,n1,x2,s2,n2\n"); fn_n++;
	printf("TV_\tt-Wert zu 2 verbundenen Gruppen, TV_ x11,x12,...,x1n,x2n\n"); fn_n++;
	printf("TWA\tTotale Wahrscheinlichkeit: pB, TWA pA1,pB|A1,...,pAn,pB|An\n"); fn_n++;
	printf("TWB\tBinomiale Wkt. p bei p, TWB p,kmin,kmax,nmin,nmax \n"); fn_n++;
	printf("TWH\tHypergmtr. Wkt. p bei K,N, TWH K,N,kmin,kmax,nmin,nmax \n"); fn_n++;
	printf("TXS\tx2-Wert zum Niveau pa2 bei df, TXS min_pa2,max_pa2,st, min_df,max_df\n"); fn_n++;
	printf("TZS\tr zw. min/max_pa2 bei min/max_n (Z-Vtlg.), TZS m_p, mx_p,st,m_n,mx_n\n"); fn_n++;
	printf("UTS_\tU-Test; U-Wert, UTS_ x1,g1,...,xn,gn; g(1,2)\n"); fn_n++;
	printf("UVS\tSimulationen zur Parameterdiff. bei 2 unverbundenen Gruppen, UVS\n"); fn_n++;
	printf("V_\tGegen-Faktorielle nV von n, V_ n \n"); fn_n++;
	printf("V_M\tVariationsmatrix von Vektor x ohne Wh zu m, V_M m, x1,...xn\n"); fn_n++;
	printf("VA_\tVarianz von Vektor x, VA_ x1,x2,...,xn\n"); fn_n++;
	printf("VAG\tGeschaetzte Populations-Varianz von Vektor x, VAG x1,x2,...,xn\n"); fn_n++;
	printf("VAX\tVarianz aus x und x2, VAX x,x2\n"); fn_n++;
	printf("VFX\t4-Felder x2, VFX a,b,c,d\n"); fn_n++;
	printf("VFYX\t4-Felder x2 kontinuitaetskorrigiert, VFYX a,b,c,d\n"); fn_n++;
	printf("VPW\tV-Wert zur Wahrscheinlichkeit p bei a und b, VPW p,a,b\n"); fn_n++;
	printf("VRW\tVariation von n mit Wiederholung zu m, VRW n,m\n"); fn_n++;
	printf("VWM\tVariationsmatrix von Vektor x mit Wh zu m, VWM m, x1,...xn\n"); fn_n++;
	printf("WP_\tWertpunktwert WP zu z-Wert, WP_ z\n"); fn_n++;
	printf("WPW\tW-Wert zur Wahrscheinlichkeit p bei a und b, WPW p,a,b\n"); fn_n++;
	printf("WTS_\tWilcoxon-Test; T-Wert, WTS_ x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("XCA\txcrit Alpha, XCA p,m0,m1,sm,df\n"); fn_n++;
	printf("XCB\txcrit Beta, XCB p,m0,m1,sm,df\n"); fn_n++;
	printf("XHF\t2^k-Felder x2 (2x2 fix), XHF z1,...,z2^k \n"); fn_n++;
	printf("XKP\tx2-Wert zur Phi Korrelation bei n, XKP r,n\n"); fn_n++;
	printf("XPW\tx2-Wert zur Wahrscheinlichkeit p bei df, XPW p,df\n"); fn_n++;
	printf("XSUM\tSumme aller xy von Matrix X, XSUM x1,y1,...,xn,yn\n"); fn_n++;
	printf("Z__\tz-Wert von a bei am und s, Z__ a,am,s\n"); fn_n++;
	printf("Z_P\tPopulations z-Wert von a zu Vektor x, Z_P a,x1,x2,...,xn\n"); fn_n++;
	printf("Z_W\tz-Wert von a zu Vektor x, Z_W a,x1,x2,...,xn\n"); fn_n++;
	printf("ZBN\tz-Wert zum binomialen 2-Felder Test, ZBN b,c\n"); fn_n++;
	printf("ZBR\tz-Wert zur Biseralen Rangkorrelation rbisR, ZBR x1,g1,...,xn,gn; g(1,2)\n"); fn_n++;
	printf("ZBS\tz-Wert zur Biseralen Korrelation rbis, ZBS x1,g1,...,xn,gn; g(1,2)\n"); fn_n++;
	printf("ZDW\tz-Wert zu Dichte d, ZDW d\n"); fn_n++;
	printf("ZEX\tz-Wert zum 4. Potenzmoment zu Vektor x, ZEX x1,x2,...,xn\n"); fn_n++;
	printf("ZFX\tz-Wert zum hypergeometrischen 4-Felder Test, ZFX a,b,c,d\n"); fn_n++;
	printf("ZKR\tz-Wert zur Partial-Korrelation rxy.z bzw. rxy.B, n, k, ZKR rxy.B,n,k \n"); fn_n++;
	printf("ZPW\tz-Wert zur Wahrscheinlichkeit p, ZPW p\n"); fn_n++;
	printf("ZRR\tz-Wert zur Korrelationsdifferenz r1-r2 bei n1,n2, ZRR r1,r2,n1,n2\n"); fn_n++;
	printf("ZSH\tz-Wert zum 3. Potenzmoment zu Vektor x, ZSH x1,x2,...,xn\n"); fn_n++;
	printf("ZTET\tz-Wert zur Tetrachorische Korrelation rtet, ZTET a,b,c,d\n"); fn_n++;
	printf("ZUTS\tU-Test; z-Wert des U-Wertes, ZUTS x1,g1,...,xn,gn; g(1,2)\n"); fn_n++;
	printf("ZWTS\tWilcoxon-Test; z-Wert des T-Wertes, ZWTS x11,x12,...,xn1,xn2\n"); fn_n++;
	for(iLauf=1; iLauf<=78; iLauf++) cprintf("\xC4"); printf("\n");
	printf("Funktionsumfang n = %i,\n",fn_n); 
	_fusszeile();

	exit(1);
};


void _funktionsindex_g()// gruppiert
{
	int iLauf;

	printf("\n");
	printf("MAT FUNKTIONSINDEX\n");
	for(iLauf=1; iLauf<=78; iLauf++) cprintf("\xC4"); printf("\n");
	printf("//\tKommentar, // Kommentar\n"); fn_n++;
	printf("R//\tKommetar in Reportdatei, R// Kommentar\n"); fn_n++;
	printf("FORM\tVorkommastellen, Stellen, Zahlenformat, FORM v,s,z; z(1=f,2=g,3=G)\n"); fn_n++;
	printf("DATX\tRohwertmatrix X Datei, DATX\n"); fn_n++;
	printf("DAT\tAusgabedatei, DAT\n"); fn_n++;
	printf("DATR\tReportdatei, DATR\n"); fn_n++;
	printf("(X)\tAusgabe in Rohwertmatrix X Datei, (X)\n"); fn_n++;
	printf("REP\tAusgabe in Reportdatei, REP\n"); fn_n++;
	printf("ABS\tAbsolutwert von x, ABS x\n"); fn_n++;
	printf("SGN\tVorzeichen von x, SGN x (-1,0,1)\n"); fn_n++;
	printf("RCP\tReziprokwert von x, 1/x, RCP x\n"); fn_n++;
	printf("INT\tGanze Zahl von x abgerundet, INT x\n"); fn_n++;
	printf("INTA\tGanze Zahl von x aufgerundet, INTA x\n"); fn_n++;
	printf("INTR\tGanze Zahl von x gerundet, INTR x\n"); fn_n++;
	printf("REST\tRest von x, REST x\n"); fn_n++;
	printf("RND\tQuasizufallszahl (Anfangswert a) in den Grenzen x,y, RND a,x,y\n"); fn_n++;
	printf("RNV\tQuasizufalls-Vektorelement px1 (Anfangswert a), RNV a,x1,...xn\n"); fn_n++;
	printf("SQU\tQuadrat von x, SQU x\n"); fn_n++;
	printf("CUB\t3. Potenz von x, CUB x\n"); fn_n++;
	printf("SQR\tQuadratwurzel von x, SQR x\n"); fn_n++;
	printf("CUR\t3. Wurzel von x, CUR x\n"); fn_n++;
	printf("PI_\tKreiskonstante, PI_\n"); fn_n++;
	printf("EUL\tEulersche Konstante, EUL\n"); fn_n++;
	printf("EXP\tEulersche Grenzwertformulierung von e zur Basis n, EXP n (0: n=1e+11)\n"); fn_n++;
	printf("LN\tLogarithmus zur Basis e von x, LN x\n"); fn_n++;
	printf("LOG\tDekadischer Logarithmus von x, LOG x\n"); fn_n++;
	printf("LGX\tLogarithmus zur Basis a von x, LGX a,x\n"); fn_n++;
	printf("RDA\tQuerdifferenz von x, RDA x\n"); fn_n++;
	printf("RDN\tReduktion von x, RDN x\n"); fn_n++;
	printf("FN1...\tTemporaergerueste zur Funktionsentwicklung, FN1 0,0\n"); fn_n++;

	
	printf("\nWinkelfunktionen\n");
	printf("RAD\tBogenmass rad von Winkel a, RAD a\n"); fn_n++;
	printf("DEG\tWinkel a von Bogenmass rad, DEG rad\n"); fn_n++;
	printf("GRAD\tNeugrad xg von Grad x, GRAD x\n"); fn_n++;
	printf("DGR\tGrad x von Neugrad xg, DGR xg\n"); fn_n++;
	printf("SIN\tSinus von x, SIN x\n"); fn_n++;
	printf("COS\tCosinus von x, COS x\n"); fn_n++;
	printf("TAN\tTangens von x, TAN x\n"); fn_n++;
	printf("COT\tCotangens von x, COT x\n"); fn_n++;
	printf("SEC\tSecans von x, SEC x\n"); fn_n++;
	printf("CSE\tCosecans von x, CSE x\n"); fn_n++;
	printf("ASN\tArcussinus von x, ASN x\n"); fn_n++;
	printf("ACS\tArcuscosinus von x, ACS x\n"); fn_n++;
	printf("ATN\tArcustangens von x, ATN x\n"); fn_n++;
	printf("ACT\tArcuscotangens von x, ACT x\n"); fn_n++;
	printf("IACT\tArcuscotangens von x iterativ, IACT x\n"); fn_n++;
	printf("ASE\tArcussecans von x, ASE x\n"); fn_n++;
	printf("IASE\tArcussecans von x iterativ, IASE x\n"); fn_n++;
	printf("ACE\tArcuscosecans von x, ACE x\n"); fn_n++;
	printf("IACE\tArcuscosecans von x iterativ, IACE x\n"); fn_n++;
	printf("HSN\tHyperbolischer Sinus von x, HSN x\n"); fn_n++;
	printf("HCS\tHyperbolischer Cosinus von x, HCN x\n"); fn_n++;
	printf("HTN\tHyperbolischer Tangens von x, HTN x\n"); fn_n++;
	printf("HCT\tHyperbolischer Cotangens von x, HCT x\n"); fn_n++;
	printf("HSE\tHyperbolischer Secans von x, HSE x\n"); fn_n++;
	printf("HCE\tHyperbolischer Cosecans von x, HCE x\n"); fn_n++;
	printf("AHS\tHyperbolischer Arcussinus von x, AHS x\n"); fn_n++;
	printf("IAHS\tHyperbolischer Arcussinus von x iterativ, IAHS x\n"); fn_n++;
	printf("AHC\tHyperbolischer Arcuscosinus von x, AHC x\n"); fn_n++;
	printf("IAHC\tHyperbolischer Arcuscosinus von x iterativ, IAHC x\n"); fn_n++;
	printf("AHT\tHyperbolischer Arcustangens von x, AHT x\n"); fn_n++;
	printf("IAHT\tHyperbolischer Arcustangens von x iterativ, IAHT x\n"); fn_n++;
	printf("AHG\tHyperbolischer Arcuscotangens von x, AHG x\n"); fn_n++;
	printf("IAHG\tHyperbolischer Arcuscotangens von x iterativ, IAHG x\n"); fn_n++;
	printf("AHN\tHyperbolischer Arcussecans von x, AHN x\n"); fn_n++;
	printf("IAHN\tHyperbolischer Arcussecans von x iterativ, IAHN x\n"); fn_n++;
	printf("AHO\tHyperbolischer Arcuscosecans von x, AHO x\n"); fn_n++;
	printf("IAHO\tHyperbolischer Arcuscosecans von x iterativ, IAHO x\n"); fn_n++;

	printf("\nStatistik\n");
	printf("N__\tWerteumfang n von Vektor x, N__ x1,x2,...,xn\n"); fn_n++;
	printf("MIN\tMinimalwert von Vektor x, MIN x1,x2,...,xn\n"); fn_n++;
	printf("MAX\tMaximalwert von Vektor x, MAX x1,x2,...,xn\n"); fn_n++;
	printf("RNG\tWertebereich von Vektor x, RNG x1,x2,...,xn\n"); fn_n++;
	printf("SUM\tSumme von Vektor x, SUM x1,x2,...,xn\n"); fn_n++;
	printf("QSUM\tSumme aller x2 von Vektor x, QSUM x1,x2,...,xn\n"); fn_n++;
	printf("XSUM\tSumme aller xy von Matrix X, XSUM x1,y1,...,xn,yn\n"); fn_n++;
	printf("PSUM\tProduktsumme von Vektor x, PSUM x1,x2,...,xn\n"); fn_n++;
	printf("RSUM\tRangsumme von Vektor x, RSUM x1,x2,...,xn\n"); fn_n++;
	printf("MR_\tRangmittel von Vektor x, MR_ x1,x2,...,xn\n"); fn_n++;
	printf("MD_\tMedian von Vektor x, MD_ x1,x2,...,xn\n"); fn_n++;
	printf("AM_\tArithmetisches Mittel von Vektor x, AM_ x1,x2,...,xn\n"); fn_n++;
	printf("AMX\tArithmetisches Mittel zu xy von Matrix X, AMX x1,y1,...,xn,yn\n"); fn_n++;
	printf("AMG\tGewichtetes Arithmetisches Mittel von Vektor x, AMG x1,n1,...,xk,nk\n"); fn_n++;
	printf("GM_\tGeometrisches Mittel von Vektor x, GM_ x1,x2,...,xn\n"); fn_n++;
	printf("HM_\tHarmonisches Mittel von Vektor x, HM_ x1,x2,...,xn\n"); fn_n++;
	printf("SD_\tStandardabweichung von Vektor x, SD_ x1,x2,...,xn\n"); fn_n++;
	printf("SDG\tGeschaetzte Populations-Stdabw von Vektor x, SDG x1,x2,...,xn\n"); fn_n++;
	printf("SDX\tGeschaetzte Populations-Stdabw von s bei n, SDX s,n\n"); fn_n++;
	printf("GSD\ts zur geschaetzten Populations-Stdabw s' bei n, GSD sg,n\n"); fn_n++;
	printf("SMG\tGeschaetzter Stdfehler des AM zu Vektor x, SMG x1,x2,...,xn\n"); fn_n++;
	printf("SMX\tGeschaetzter Stdfehler des AM zu Vektor x aus s und n, SMX s,n\n"); fn_n++;
	printf("GSM\ts zum geschaetzten Stdfehler des AM bei n, GSM smg,n\n"); fn_n++;
	printf("VA_\tVarianz von Vektor x, VA_ x1,x2,...,xn\n"); fn_n++;
	printf("VAX\tVarianz aus x und x2, VAX x,x2\n"); fn_n++;
	printf("VAG\tGeschaetzte Populations-Varianz von Vektor x, VAG x1,x2,...,xn\n"); fn_n++;
	printf("GVA\ts zur geschaetzten Populations-Varianz bei n, GVA s2g,n\n"); fn_n++;
	printf("SDV\tVariationsquotient v von Vektor x, SDV x1,x2,...,xn, \n"); fn_n++;
	printf("D__\tSchrausser's d von Vektor x, D__ x1,x2,...,xn\n"); fn_n++;
	printf("DVARO\tVarianzoberflaeche von Vektor x, DVARO x1,x2,...,xn\n"); fn_n++;
	printf("Z_W\tz-Wert von a zu Vektor x, Z_W a,x1,x2,...,xn\n"); fn_n++;
	printf("Z_P\tPopulations z-Wert von a zu Vektor x, Z_P a,x1,x2,...,xn\n"); fn_n++;
	printf("Z__\tz-Wert von a bei am und s, Z__ a,am,s\n"); fn_n++;
	printf("SCH\t3. Potenzmoment zu Vektor x, SCH x1,x2,...,xn\n"); fn_n++;
	printf("SHP\t3. Potenzmoment zu Vektor x (Pop.), SHP x1,x2,...,xn\n"); fn_n++;
	printf("EXZ\t4. Potenzmoment zu Vektor x, EXZ x1,x2,...,xn\n"); fn_n++;
	printf("EZP\t4. Potenzmoment zu Vektor x (Pop.), EZP x1,x2,...,xn\n"); fn_n++;
	printf("SSH\tStandardfehler des 3. Potenzmoments bei n, SSH n\n"); fn_n++;
	printf("SEX\tStandardfehler des 4. Potenzmoments bei n, SEX n\n"); fn_n++;
	printf("SW_\tStandardnormwert Z zu z-Wert, SW_ z\n"); fn_n++;
	printf("PR_\tProzentrang PR zu z-Wert, PR_ z\n"); fn_n++;
	printf("IQ_\tIQ-Norm Wert zu z-Wert, IQ_ z\n"); fn_n++;
	printf("IQK\tIQ-Norm Wert fuer Kinder zu z-Wert, IQK z\n"); fn_n++;
	printf("WP_\tWertpunktwert WP zu z-Wert, WP_ z\n"); fn_n++;
	printf("CW_\tC-Norm Wert zu z-Wert, CW_ z\n"); fn_n++;
	printf("S__\tStanine-Norm Wert S zu z-Wert, S__ z\n"); fn_n++;
	printf("STN\tSten-Norm Wert zu z-Wert, STN z\n"); fn_n++;
	printf("SN_\tStandardnotenwert N zu z-Wert, SN_ z\n"); fn_n++;
	printf("T__\tT-Norm Wert zu z-Wert bei Normalverteilung, T__ z\n"); fn_n++;

	printf("\nLineare Regression\n");
	printf("COV\tKovarianz s2xy von x und y zur Matrix X, COV x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("COX\tKovarianz s2xy aus x, y und xy, COX x,y,xy \n"); fn_n++;
	printf("KOR\tKorrelationskoeffizient rxy zur Matrix X, KOR x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("KOX\tKorrelationskoeffizient rxy aus x,y,x2,y2,xy, KOX x,y,x2,y2,xy\n"); fn_n++;
	printf("RYX\tRegressionskoeffizient ryx zur Matrix X, RYX x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("KRS\tRangkorrelation rs zur Matrix X, KRS x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("KPH\tPhi Korrelation, KPH a,b,c,d\n"); fn_n++;
	printf("KPM\tPhi Korrelation maximal, KPM a,b,c,d\n"); fn_n++;
	printf("KTET\tTetrachorische Korrelation rtet, KTET a,b,c,d\n"); fn_n++;
	printf("STET\tStandardfehler stet zur Tetrachorische Korrelation rtet, STET a,b,c,d\n"); fn_n++;
	printf("KPB\tPunktbiserale Korrelation rpb, KPB x1,g1,...,xn,gn; g(1,2)\n"); fn_n++;
	printf("KBS\tBiserale Korrelation rbis, KBS x1,g1,...,xn,gn; g(1,2)\n"); fn_n++;
	printf("SBS\tStandardfehler srbis zur rbis, SBS x1,g1,...,xn,gn; g(1,2)\n"); fn_n++;
	printf("BSK\tBiserale Korrelation rbis zur Korrelation rpb bei n1, n2, BSK r,n1,n2\n"); fn_n++;
	printf("KBR\tBiserale Rangkorrelation rbisR, KBR x1,g1,...,xn,gn; g(1,2)\n"); fn_n++;
	printf("DET\tDeterminationskoeffizient der Vektoren x und y, DET x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("RED\tRedundanz von y, Red(yx), RED x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("BYX\tRegressionskoeffizient byx, F(x)=y=byx*x+ayx, BYX x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("AYX\tRegressionskoeffizient ayx, F(x)=y=byx*x+ayx, AYX x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("BXY\tRegressionskoeffizient bxy, F(y)=x=bxy*y+axy, BXY x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("AXY\tRegressionskoeffizient axy, F(y)=x=bxy*y+axy, AXY x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("PKR\tPartial-Korrelationskoeffizient rxy.z, PKR rxy,rxz,ryz\n"); fn_n++;
	printf("PKRB\tPartial-Korrelationskoeffizient rxy.B, PKRB RyxB,RyB\n"); fn_n++;
	printf("PKS\tSemipartial-Korrelationskoeffizient ry(x.z), rx(y.z), PKS rxy,rxz,ryz\n"); fn_n++;
	printf("MKR\tMultipler-Korrelationskoeffizient Rc,12, MKR r1c,r2c,r12\n"); fn_n++;
	printf("PKSB\tSemipartial-Korrelationskoeffizient ry(x.B), rx(y.B), PKSB RyxB,RyB \n"); fn_n++;
	printf("MKRN\tMultipler-Korrelationskoeff. Rc,12...k, MKRN b1,b2,..,bk,r1c,r2c,..,rkc\n"); fn_n++;
	printf("BMK\tBetagewicht b zu Rc,12...k, BMK i,k,r1c,r2c,...,rkc,r12,...,r1k,...,rik\n"); fn_n++;
	printf("MBC\tRohwertgewicht bc, MBC sc,bi,si\n"); fn_n++;
	printf("MAC\tMultipler Regressionskoeff. ac,12...k, MAC xc,sc,b1,x1,s1,...,bk,xk,sk\n"); fn_n++;
	printf("SKM\tSchrumpfungskorrektur zu R bei gegebenem n und k, SKM R,n,k\n"); fn_n++;
	printf("PKRB\tMultipler Partial- Rc,A.B, PKRB RcAB,RcB\n"); fn_n++;
	printf("PKSB\tMultipler Semipartial-Rc,(A.B), PKSB RcAB,RcB \n"); fn_n++;
	
	printf("\nMatrizenrechnung\n");
	printf("MXA\tMatr.-Additions Element cij, MXA i,j,n,a11,.,a1k,.,ank,b11,.,b1k,.,bnk\n"); fn_n++;
	printf("MXS\tMatr.-Subtraktions Elmt xij, MXS i,j,n,b11,.,b1k,.,bnk,a11,.,a1k,.,ank\n"); fn_n++;
	printf("MXM\tMatr.-Multipl Elmt cij, MXM i,j,n1,k1,a11,.,a1k,.,ank,b11,.,b1m,.,bkm\n"); fn_n++;
	printf("MXQ\tMatr.-Quadrierungs Elmt cij, MXA i,j,n1,k1,a11,.,a1k,.,ank\n"); fn_n++;
	printf("MXT\tMatrizen-Transponierungs Element aij, MXT i,j,n,a11,...,a1k,...,ank\n"); fn_n++;
	printf("MXI\tMatrizen-Inversions Element aij, MXI i,j,n,a11,...,a1n,...,ann\n"); fn_n++;
	printf("MRI\tMatrizen-Inversions Element rii zu R-1, MRI i,k,r12,...,r1k,...,rik\n"); fn_n++;
	printf("MSP\tSpur spA einer quadratischen Matrix A, MSP n,a11,...,a1n,...,ann\n"); fn_n++;
	printf("MDT\tDeterminante detA von Matrix A, MDT n,a11,...,a1n,...,ann\n"); fn_n++;
	printf("MXV\tMatrizen-Verkettungs Element b/cij, MXV i,j,n,a11,...,a1n,...,ann\n"); fn_n++;
	
	printf("\nVerteilungsfunktionen\n");
	printf("IGM\tGamma Integrale zu x bei d, IGM x, d\n"); fn_n++;
	printf("DGM\tGamma Dichte bei x und t, DGM x, t\n"); fn_n++;
	printf("GAMMA\tGamma von x, GAMMA x\n"); fn_n++;
	printf("AGAM\tInvers Alpha-Gamma von Gamma, AGAM g\n"); fn_n++;
	printf("BGAM\tInvers Beta-Gamma von Gamma, BGAM g\n"); fn_n++;
	printf("DGAM\tGamma Verteilungs-Dichte zu x bei c, DGAM x,c\n"); fn_n++;
	printf("TPW\tt-Wert zur Wahrscheinlichkeit p bei df, TPW p,df\n"); fn_n++;
	printf("PTW\tWahrscheinlichkeit p bei df zu t-Wert, PTW t,df\n"); fn_n++;
	printf("DTW\tDichte d bei df zu t-Wert, DTW t,df\n"); fn_n++;
	printf("PTD\tWahrscheinlichkeit p bei df zu t-Wert (Dichteintegral), PTD t,df\n"); fn_n++;
	printf("XPW\tx2-Wert zur Wahrscheinlichkeit p bei df, XPW p,df\n"); fn_n++;
	printf("PXW\tWahrscheinlichkeit p bei df zu x2-Wert, PXW x,df\n"); fn_n++;
	printf("DXW\tDichte d bei df zu x2-Wert, DXW x,df\n"); fn_n++;
	printf("PXD\tWahrscheinlichkeit p bei df zu x2-Wert (Dichteintegral), PXD x,df\n"); fn_n++;
	printf("FPW\tF-Wert zur Wahrscheinlichkeit p bei df1 und df2, FPW p,df1,df2\n"); fn_n++;
	printf("PFW\tWahrscheinlichkeit p bei df1 und df2 zu F-Wert, PFW f,df1,df2\n"); fn_n++;
	printf("DFW\tDichte d bei df1 und df2 zu F-Wert, DFW F,df1,df2\n"); fn_n++;
	printf("PFD\tWahrscheinlichkeit p bei df12 zu F-Wert (Dichteintegral), PFD F,df1,df2\n"); fn_n++;
	printf("ZPW\tz-Wert zur Wahrscheinlichkeit p, ZPW p\n"); fn_n++;
	printf("PZW\tWahrscheinlichkeit p zu z-Wert, PZW z\n"); fn_n++;
	printf("DZW\tDichte d zu z-Wert, DZW z\n"); fn_n++;
	printf("ZDW\tz-Wert zu Dichte d, ZDW d\n"); fn_n++;
	printf("PZD\tWahrscheinlichkeit p zu z-Wert (Dichteintegral), PZD z\n"); fn_n++;
	printf("APW\tA-Wert zur Wahrscheinlichkeit p bei a und b, APW p,a,b\n"); fn_n++;
	printf("PAW\tWahrscheinlichkeit p bei a und b zu A-Wert, PAW A,a,b\n"); fn_n++;
	printf("DAW\tDichte d bei a und b zu A-Wert, DAW A,a,b\n"); fn_n++;
	printf("CPW\tX-Wert zur Wahrscheinlichkeit p bei a und b, CPW p,a,b\n"); fn_n++;
	printf("PCW\tWahrscheinlichkeit p bei a und b zu X-Wert, PCW X,a,b\n"); fn_n++;
	printf("DCW\tDichte d bei a und b zu X-Wert, DCW X,a,b\n"); fn_n++;
	printf("LPW\tL-Wert zur Wahrscheinlichkeit p bei a und b, LPW p,a,b\n"); fn_n++;
	printf("PLW\tWahrscheinlichkeit p bei a und b zu L-Wert, PLW L,a,b\n"); fn_n++;
	printf("DLW\tDichte d bei a und b zu L-Wert, DLW L,a,b\n"); fn_n++;
	printf("VPW\tV-Wert zur Wahrscheinlichkeit p bei a und b, VPW p,a,b\n"); fn_n++;
	printf("PVW\tWahrscheinlichkeit p bei a und b zu V-Wert, PVW V,a,b\n"); fn_n++;
	printf("DVW\tDichte d bei a und b zu V-Wert, DVW V,a,b\n"); fn_n++;
	printf("WPW\tW-Wert zur Wahrscheinlichkeit p bei a und b, WPW p,a,b\n"); fn_n++;
	printf("PWW\tWahrscheinlichkeit p bei a und b zu W-Wert, PWW W,a,b\n"); fn_n++;
	printf("DWW\tDichte d bei a und b zu W-Wert, DWW W,a,b\n"); fn_n++;
	printf("ZSH\tz-Wert zum 3. Potenzmoment zu Vektor x, ZSH x1,x2,...,xn\n"); fn_n++;
	printf("ZEX\tz-Wert zum 4. Potenzmoment zu Vektor x, ZEX x1,x2,...,xn\n"); fn_n++;
	printf("FZR\tFishers Z zum Korrelationskoeffizienten r, FZR r\n"); fn_n++;
	printf("RFZ\tKorrelationskoeffizient r zu Fishers Z, RFZ Z\n"); fn_n++;
	printf("SFZ\tStandardabweichung zu Fishers Z bei n, SFZ n\n"); fn_n++;
	printf("GFZ\tGemitteltes Fisher Z, GFZ Z1, nr1,..., Zk,nrk\n"); fn_n++;
	printf("TRW\tt-Wert zur Korrelation r bei n, TRW r,n\n"); fn_n++;
	printf("TKV\tt-Wert zur Varianzdiff. korr. Vektoren x und y, TKV x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("RPT\tKorrelationskoeffizient r zu Niveau pa2  bei n (t-Vtlg.), RPT pa2,n\n"); fn_n++;
	printf("RPZ\tKorrelationskoeffizient r zu Niveau pa2  bei n (Z-Vtlg.), RPZ pa2,n\n"); fn_n++;
	printf("XKP\tx2-Wert zur Phi Korrelation bei n, XKP r,n\n"); fn_n++;
	printf("ZTET\tz-Wert zur Tetrachorische Korrelation rtet, ZTET a,b,c,d\n"); fn_n++;
	printf("ZBS\tz-Wert zur Biseralen Korrelation rbis, ZBS x1,g1,...,xn,gn; g(1,2)\n"); fn_n++;
	printf("ZBR\tz-Wert zur Biseralen Rangkorrelation rbisR, ZBR x1,g1,...,xn,gn; g(1,2)\n"); fn_n++;
	printf("ZRR\tz-Wert zur Korrelationsdifferenz r1-r2 bei n1,n2, ZRR r1,r2,n1,n2\n"); fn_n++;
	printf("ZKR\tz-Wert zur Partial-Korrelation rxy.z bzw. rxy.B, n, k, ZKR rxy.B,n,k \n"); fn_n++;
	printf("KRP\tPartial-Korrelationskoeff. rxy.B zu pa2 bei n, k (Z-Vtlg.), KRP pa2,n,k\n"); fn_n++;
	printf("FMK\tF-Wert zu R bei gegebenem n und k, FMK R,n,k\n"); fn_n++;
	printf("MKP\tMultipler-Korrelationskoeffizient R zu Niveau pa2 bei n, k, MKP pa2,n,k\n"); fn_n++;
	printf("TBM\tt-Wert zu bi, Element rii von R-1 zu R bei n, k, TBM bi,rii,R,n,k\n"); fn_n++;
	printf("FMP\tF-Wert zu Rc,A.B u. Rc,(A.B) mit n, kA, pB, FMP RcAB, RcB, n,k,p \n"); fn_n++;
	printf("TT_\tt-Wert fuer 1 Gruppe bei x, s und n zur Pruefgroesse y, TT_ x,s,n,y\n"); fn_n++;
	printf("TU_\tt-Wert zu 2 unverbundenen Gruppen, TU_ x1,g1,...,xn,gn; g(1,2)\n"); fn_n++;
	printf("TUX\tt-Wert zu 2 unverbundenen Gruppen, TUX x1,s1,n1,x2,s2,n2\n"); fn_n++;
	printf("TV_\tt-Wert zu 2 verbundenen Gruppen, TV_ x11,x12,...,x1n,x2n\n"); fn_n++;
	printf("UTS_\tU-Test; U-Wert, UTS_ x1,g1,...,xn,gn; g(1,2)\n"); fn_n++;
	printf("SUTS\tU-Test; Standardfehler sU, SUTS x1,g1,...,xn,gn; g(1,2)\n"); fn_n++;
	printf("MUTS\tU-Test; Populationswert mU, MUTS x1,g1,...,xn,gn; g(1,2)\n"); fn_n++;
	printf("ZUTS\tU-Test; z-Wert des U-Wertes, ZUTS x1,g1,...,xn,gn; g(1,2)\n"); fn_n++;
	printf("WTS_\tWilcoxon-Test; T-Wert, WTS_ x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("SWTS\tWilcoxon-Test; Standardfehler sT, SWTS x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("MWTS\tWilcoxon-Test; Populationswert mT, MWTS x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("ZWTS\tWilcoxon-Test; z-Wert des T-Wertes, ZWTS x11,x12,...,xn1,xn2\n"); fn_n++;
	printf("EDX\tEindimensionales x2, EDX h1,h2,...,hn\n"); fn_n++;
	printf("VFX\t4-Felder x2, VFX a,b,c,d\n"); fn_n++;
	printf("VFYX\t4-Felder x2 kontinuitaetskorrigiert, VFYX a,b,c,d\n"); fn_n++;
	printf("ZFX\tz-Wert zum hypergeometrischen 4-Felder Test, ZFX a,b,c,d\n"); fn_n++;
	printf("MNX\tMcNemar x2, MNX b,c\n"); fn_n++;
	printf("MNYX\tMcNemar x2 kontinuitaetskorrigiert, MNYX b,c\n"); fn_n++;
	printf("ZBN\tz-Wert zum binomialen 2-Felder Test, ZBN b,c\n"); fn_n++;
	printf("KLX\tkxl-Felder x2, KL2 Z,S,z11,..,z1S,..,zZ1,..,zZS\n"); fn_n++;
	printf("KFA\t2^k-Felder x2, KFA z11,...,z2^k\n"); fn_n++;
	printf("XHF\t2^k-Felder x2 (2x2 fix), XHF z1,...,z2^k \n"); fn_n++;
	printf("CQT\tCochran Q-Test, CQT nT,T1,...,Tm,L1,...,Ln\n"); fn_n++;
	printf("CI_\tHalber Vertrauensbereich ci zu P CI bei sm und df, CI_ P,sm,df\n"); fn_n++;
	printf("EFG\tEffektgroesse e, EFG m0,m1,sg\n"); fn_n++;
	printf("XCA\txcrit Alpha, XCA p,m0,m1,sm,df\n"); fn_n++;
	printf("XCB\txcrit Beta, XCB p,m0,m1,sm,df\n"); fn_n++;
	printf("ANI\tAlpha Niveau p, ANI x,m0,sm,df \n"); fn_n++;
	printf("BNI\tBeta Niveau p, BNI x,m1,sm,df \n"); fn_n++;
	printf("IMB\tTeststaerke 1-Beta, IMB x,m1,sm,df\n"); fn_n++;
	printf("OPN\tOptimaler Stichprobenumfang nopt, OPN p,e,df\n"); fn_n++;
	printf("EFS\tEffektstaerke ep, EFS p,n,df\n"); fn_n++;
	printf("OPP\tOptimales Alpha Niveau popt, OPP, e,n,df\n"); fn_n++;
	printf("ONZ\tOptimaler Stichprobenumfang nopt (z-Vtlg.), ONZ p,e\n"); fn_n++;
	printf("SWX\tSchwellenwert xcrit, SWX m0,m1,sg,n\n"); fn_n++;
	printf("SIG\t2-seitiges Signifikanzniveau zu z- oder t-Wert bei p, SIG p\n"); fn_n++;


	printf("\nWahrscheinlichkeit und Kombinatorik\n");
	printf("!/FACT\tFaktorielle von n, ! n / FACT n\n"); fn_n++;
	printf("!!\tDoppelfaktorielle von n, !! n \n"); fn_n++;
	printf("!.!\tTripelfaktorielle von n, !.! n \n"); fn_n++;
	printf("V_\tGegen-Faktorielle nV von n, V_ n \n"); fn_n++;
	printf(";\t() Binomialkoeffizient n ueber k, ; n,k\n"); fn_n++;
	printf("MPW\tMultiplikative Wkt unabh: p alle Ereignisse, MPW pA1,...,pAn\n"); fn_n++;
	printf("MPW\tMultiplikative Wkt abh: p alle Ereignisse, MPW pA1,pA2|A1,..,pAn|A1..n\n"); fn_n++;
	printf("AAA\tAdditive Wkt ausschl abh: p ein Ereignis, AAA pA1,...,pAn\n"); fn_n++;
	printf("AEU\tAdditive Wkt einschl unabh: p mindestens ein E, AEU pA1,...,pAn\n"); fn_n++;
	printf("AWN\tAdditive Wkt: A mindestens 1 mal bei n, AWN pA,n\n"); fn_n++;
	printf("AEA\tAdditive Wkt einschl abh: p ein oder beide E, AEA pA, pB, pAB\n"); fn_n++;
	printf("BWA\tBedingte Wkt: B unter der Bedingung von A, BWA pA,pAB \n"); fn_n++;
	printf("TWA\tTotale Wahrscheinlichkeit: pB, TWA pA1,pB|A1,...,pAn,pB|An\n"); fn_n++;
	printf("BYS\tBayes Formulierung, BYS pA1,pB|A1,...,pAn,pB|An\n"); fn_n++;
	printf("BNP\tBinomial Punkt-Wahrscheinlichkeit, p genau k mal von n, BNP p,k,n\n"); fn_n++;
	printf("BNW\tBinomial Wahrscheinlichkeit, p hoechstens (<=) k mal von n, BNW p,k,n\n"); fn_n++;
	printf("BNM\tMittelwert zur Binomialverteilung, BNM p,n\n"); fn_n++;
	printf("BNS\tStreuung zur Binomialverteilung, BNS p,n\n"); fn_n++;
	printf("MNP\tMultinomial Punkt-Wahrscheinlichkeit, MNP p1,k1,...,ps,ks,n\n"); fn_n++;
	printf("PNP\tPoisson Punkt-Wahrscheinlichkeit, p genau k mal von n, PNP p,k,n\n"); fn_n++;
	printf("PNW\tPoisson Wahrscheinlichkeit, p hoechstens (<=) k mal von n, PNW p,k,n\n"); fn_n++;
	printf("NBP\tNegative Binomial Punkt Wkt., p das kte mal bei r+k, NBP p,k,r+k\n"); fn_n++;
	printf("NBW\tNegative Binomial Wkt., p hoechstens das kte mal bei r+k, NBN p,k,r+k\n"); fn_n++;
	printf("GMP\tGeometrische Punkt-Wkt., pA das 1. mal bei r+1, GMP p,r+1\n"); fn_n++;
	printf("GMW\tGeometrische Wkt., pA das 1. mal bis (<=) r+1, GMW p,r+1\n"); fn_n++;
	printf("HGP\tHypergeometrische Punkt-Wkt., kA von n von N mit KA, HGP k,n,N,K\n"); fn_n++;
	printf("HGW\tHypergeometrische Wkt., <= kA von n von N mit KA, HGW k,n,N,K\n"); fn_n++;
	printf("HGM\tMittelwert zur hypergeometrischen Verteilung, HGM n,K,N\n"); fn_n++;
	printf("HGS\tStreuung zur hypergeometrischen Verteilung, HGS n,K,N\n"); fn_n++;
	printf("NPR/VR_\tVariation von n ohne Wiederholung zu m, NPR n,m / VR_ n,m\n"); fn_n++;
	printf("VRW\tVariation von n mit Wiederholung zu m, VRW n,m\n"); fn_n++;
	printf("PM_\tPermutation von n ohne Klassen, PM_ n\n"); fn_n++;
	printf("PMW\tPermutation von n zu den Klassen k1,k2,...km, PMW n,k1,k2,...,km\n"); fn_n++;
	printf("NCR/KM_\tKombination von n ohne Wiederholung zu m, NCR n,m / KM_ n,m\n"); fn_n++;
	printf("KMW\tKombination von n mit Wiederholung zu m, KMW n,m\n"); fn_n++;
	printf("K_M\tKombinationsmatrix von Vektor x ohne Wh zu m, K_M m, x1,...xn\n"); fn_n++;
	printf("KWM\tKombinationsmatrix von Vektor x mit Wh zu m, KWM m, x1,...xn\n"); fn_n++;
	printf("V_M\tVariationsmatrix von Vektor x ohne Wh zu m, V_M m, x1,...xn\n"); fn_n++;
	printf("VWM\tVariationsmatrix von Vektor x mit Wh zu m, VWM m, x1,...xn\n"); fn_n++;
	printf("P_M\tPermutationsmatrix von Vektor x zu 1 Klasse, P_M x1,...xn\n"); fn_n++;
	printf("P2M\tPermutationsmatrix von Vektor x zu 2 Klassen, P2M k1,k2,x1,...xn\n"); fn_n++;
	printf("PMM\tPermutationsmatrix von Vektor x zu m Klassen, PMM k1,...,km,x1,...xn\n"); fn_n++;
	printf("BN0\tBinomial Test; Binomial Punkt-Wkt. P0, BN0 b,c\n"); fn_n++;
	printf("BN1\tBinomial Test; Exakt 1-seitiges Niveau pexact1, BN1 b,c\n"); fn_n++;
	printf("BN2\tBinomial Test; Exakt 2-seitiges Niveau pexact2, BN2 b,c\n"); fn_n++;
	printf("MN0\tk-Felder; Multinomiale Punkt-Wkt, MN0 z1,...,zk\n"); fn_n++;
	printf("MN2\tk-Felder; Exakt 2-seitiges Niveau pexact2, MN2 z1,...,zk\n"); fn_n++;
	printf("FX0\tFisher Exact Test; Hypergeometrische Punkt-Wkt. P0, FX0 a,b,c,d\n"); fn_n++;
	printf("FX1\tFisher Exact Test; Exakt 1-seitiges Niveau pexact1, FX1 a,b,c,d\n"); fn_n++;
	printf("FX2\tFisher Exact Test; Exakt 2-seitiges Niveau pexact2, FX2 a,b,c,d\n"); fn_n++;
	printf("KL0\tkxl Test; Hypergeom. Punkt-Wkt, KL0 Z,S,z11,..,z1S,..,zZ1,..,zZS\n"); fn_n++;
	printf("KL2\tkxl Test; Exakt 2-seitiges Niv pexact2, KL2 Z,S,z11,.,z1S,.,zZ1,.,zZS\n"); fn_n++;
	printf("CKL\tKombinationen zum kxl-Felder Test, CKL k,l,z11,...,z1S,...,zZ1,...,zZS\n"); fn_n++;
	printf("HG0\t2^k Test; Hypergeometrische Punkt-Wkt, HG0 z1,...,z2k \n"); fn_n++;
	printf("HG2\t2^k Test; Exakt 2-seitiges Niveau pexact2, HG2 z1,...,z2k \n"); fn_n++;
	printf("CHG\tKombinationen zum 2^k-Felder Test, CHG z1,...,z2k \n"); fn_n++;
	printf("HF0\t2^k Test (2x2 fix); Hypergeometrische Punkt-Wkt, HF0 z1,...,z2k \n"); fn_n++;
	printf("HF2\t2^k Test (2x2 fix); Exakt 2-seitiges Niveau pexact2, HF2 z1,...,z2k \n"); fn_n++;
	printf("CHF\tKombinationen zum 2^k-Felder Test (2x2 fix), CHF z1,...,z2k \n"); fn_n++;

	printf("\nRandomisation und Datensimulationsmodelle \n");
	printf("RNN\tZufallsvektor n nach Verteilung F(n), RNN\n"); fn_n++;
	printf("RNB\tZufallsmatrix N nach bivariater Verteilung, RNB\n"); fn_n++;
	printf("UVS\tSimulationen zur Parameterdiff. bei 2 unverbundenen Gruppen, UVS\n"); fn_n++;
	printf("APX\tKurvenanpassungsprozeduren, APX\n"); fn_n++;
	printf("BSM\tBinomialsimulationen, BSM\n"); fn_n++;
	printf("HSM\tHypergeometrische Simulationen, HSM\n"); fn_n++;
	printf("LTO\tLotto Simulation1, LTO k,N,z1,...,z6\n"); fn_n++;
	printf("LTO\tLotto Simulation2, LTO N,M,z1,...,z6\n"); fn_n++;
	printf("RLT\tRoulettesimulationen, RLT\n"); fn_n++;

	printf("\nTabellen\n");
	printf("TBZ\tz-Wert zw. min_z und max_z in st Stufen, TBZ min_z,max_z,st\n"); fn_n++;
	printf("TPZ\tProzentrang p zu z-Wert zw. min_z und max_z in st , TPZ min_z,max_z,st\n"); fn_n++;
	printf("T1Z\t1-stgs. Niveau zu z-Wert zw. min_z und max_z in st , T1Z min_z,max_z,st\n"); fn_n++;
	printf("T2Z\t2-stgs. Niveau zu z-Wert zw. min_z und max_z in st , T2Z min_z,max_z,st\n"); fn_n++;
	printf("TDZ\tDichte d zu z-Wert zw. min_z und max_z in st , TDZ min_z,max_z,st\n"); fn_n++;
	printf("TBT\tt-Wert zw. min_t und max_t in st Stufen, TBT min_t,max_t,st\n"); fn_n++;
	printf("TPT\tProzentrang p zw. min_t und max_t in st bei df , TPT min_t,max_t,st,df\n"); fn_n++;
	printf("T1T\t1-stgs. Niveau zw. min_t und max_t in st bei df, T1T min_t,max_t,st,df\n"); fn_n++;
	printf("T2T\t2-stgs. Niveau zw. min_t und max_t in st bei df, T2T min_t,max_t,st,df\n"); fn_n++;
	printf("TDT\tDichte d zw. min_t und max_t in st bei df, TDT min_t,max_t,st,df\n"); fn_n++;
	printf("TTS\tt-Wert zum Niveau pa2 bei df, TTS min_pa2,max_pa2,st, min_df,max_df\n"); fn_n++;
	printf("TBX\tx2-Wert zw. min_x und max_x in st Stufen, TBX min_x,max_x,st\n"); fn_n++;
	printf("TPX\tProzentrang p zw. min_x und max_x in st bei df , TPX min_x,max_x,st,df\n"); fn_n++;
	printf("T1X\t1-stgs. Niveau zw. min_x und max_x in st bei df, T1X min_x,max_x,st,df\n"); fn_n++;
	printf("T2X\t2-stgs. Niveau zw. min_x und max_x in st bei df, T2X min_x,max_x,st,df\n"); fn_n++;
	printf("TDX\tDichte d zw. min_x und max_x in st bei df, TDX min_x,max_x,st,df\n"); fn_n++;
	printf("TXS\tx2-Wert zum Niveau pa2 bei df, TXS min_pa2,max_pa2,st, min_df,max_df\n"); fn_n++;
	printf("TBF\tF-Wert zw. min_F und max_F in st Stufen, TBF min_F,max_F,st\n"); fn_n++;
	printf("TPF\tProzentrang p zw. min_F und max_F, TPF min_F,max_F,st,df1,df2\n"); fn_n++;
	printf("T1F\t1-stgs. Niveau zw. min_F und max_F, T1F min_F,max_F,st,df1,df2\n"); fn_n++;
	printf("T2F\t2-stgs. Niveau zw. min_F und max_F, T2F min_F,max_F,st,df1,df2\n"); fn_n++;
	printf("TDF\tDichte d zw. min_F und max_F, TDF min_F,max_F,st,df1,df2\n"); fn_n++;
	printf("TFS\tF-Wert zum Niveau pa2 bei df1,2, TFS pa2,mn_df1,mx_df1,mn_df2,mx_df2\n"); fn_n++;
	printf("TBB\tBinomiale Punkt-Wkt. P0 bei p, TBB p,kmin,kmax,nmin,nmax \n"); fn_n++;
	printf("TWB\tBinomiale Wkt. p bei p, TWB p,kmin,kmax,nmin,nmax \n"); fn_n++;
	printf("T1B\tBinomiales Niveau pexact1 bei p, T1B p,kmin,kmax,nmin,nmax \n"); fn_n++;
	printf("T2B\tBinomiales Niveau pexact2 bei p, T2B p,kmin,kmax,nmin,nmax \n"); fn_n++;
	printf("TBH\tHypergmtr. Punkt-Wkt. P0 bei K,N, TBH K,N,kmin,kmax,nmin,nmax \n"); fn_n++;
	printf("TWH\tHypergmtr. Wkt. p bei K,N, TWH K,N,kmin,kmax,nmin,nmax \n"); fn_n++;
	printf("T1H\tHypergmtr. Niveau pexact1 bei K,N, T1H K,N,kmin,kmax,nmin,nmax \n"); fn_n++;
	printf("T2H\tHypergmtr. Niveau pexact2 bei K,N, T2H K,N,kmin,kmax,nmin,nmax \n"); fn_n++;
	printf("TCH\tKombinationen 2x2C bei K,N, TCH K,N,kmin,kmax,nmin,nmax \n"); fn_n++;
	printf("TBR\tn Quasizufallszahlen (Anfangsw.=a) in den Grenzen x,y, TBR a,x,y,n\n"); fn_n++;
	printf("TPK\tProzentranges p zur Korrelation r, TPK rmin,rmax,nmin,nmax,st\n"); fn_n++;
	printf("T1K\t1-seitiges Niveau pa1 zur Korrelation r, T1K rmin,rmax,nmin,nmax,st\n"); fn_n++;
	printf("T2K\t2-seitiges Niveau pa2 zur Korrelation r, T2K rmin,rmax,nmin,nmax,st\n"); fn_n++;
	printf("TRS\tr zw. min/max_pa2 bei min/max_n (t-Vtlg.), TRS m_p, mx_p,st,m_n,mx_n\n"); fn_n++;
	printf("TZS\tr zw. min/max_pa2 bei min/max_n (Z-Vtlg.), TZS m_p, mx_p,st,m_n,mx_n\n"); fn_n++;
	printf("TMS\tR zw. min/max_pa2 bei min/max_n und k, TMS m_p, mx_p,st,m_n,mx_n,k\n"); fn_n++;
	printf("TPS\trxy.B zw. min/max_pa2 bei min/max_n und k, TPS m_p, mx_p,st,m_n,mx_n,k\n"); fn_n++;
	printf("TPE\tpopt zw. min/max_e in st bei min/max_n, TPE m_e,mx_e,st,m_n,mx_n\n"); fn_n++;
	printf("TNE\tnopt zw. min/max_e in st bei min/max_pa2, TNE m_e,mx_e,st,m_pa2,mx_pa2\n"); fn_n++;
	printf("TEE\teopt zw. min/max_pa2 in st bei min/max_n, TEE m_pa2,mx_pa2,st,m_n,mx_n\n"); fn_n++;

	for(iLauf=1; iLauf<=78; iLauf++) cprintf("\xC4"); printf("\n");
	printf("Funktionsumfang n = %i,\n",fn_n); 
	_fusszeile();
	exit(1);
};

void _fusszeile()
{
	printf("Mathematisch-statistischer Algorithmus Interpreter,\n"); 
	printf("MAT von Dietmar Schrausser. (c) 2009 - 2011 SCHRAUSSER Soft.\n");
}

