//----------------------------------------------------------------------------------------------------| MAT header, SCHRAUSSER 2009	//   
//																										

void klammer_()
{
	if (iLauf > 1 && arg_[iLauf] == '(')
		if ( arg_[iLauf-1] != '+' )  
		 if ( arg_[iLauf-1] != '-' )
		  if ( arg_[iLauf-1] != '*' ) 
		   if ( arg_[iLauf-1] != '/' ) 
			if ( arg_[iLauf-1] != '%' ) 
			 if ( arg_[iLauf-1] != 'h' )
			  if ( arg_[iLauf-1] != 'v' ) 
			   if ( arg_[iLauf-1] != '!' ) //-----------------------------------------------------> funktionsbezeichner vor klammer
			   if(( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'B' &&  arg_[iLauf-1] != 'S')
			   && ( arg_[iLauf-3] != 'L'  &&  arg_[iLauf-2] != 'O' &&  arg_[iLauf-1] != 'G')
			   && ( arg_[iLauf-2] != 'L'  &&  arg_[iLauf-1] != 'N' )     
			   && ( arg_[iLauf-3] != 'I'  &&  arg_[iLauf-2] != 'N' &&  arg_[iLauf-1] != 'T')
			     
			   && ( arg_[iLauf-4] != 'I'  &&  arg_[iLauf-3] != 'N' &&  arg_[iLauf-2] != 'T' && (arg_[iLauf-1] != 'A'  
																							||  arg_[iLauf-1] != 'R' )) 
			   
			   && ( arg_[iLauf-4] != 'R'  &&  arg_[iLauf-3] != 'E' &&  arg_[iLauf-2] != 'S' &&  arg_[iLauf-1] != 'T')
			   && ( arg_[iLauf-4] != 'F'  &&  arg_[iLauf-3] != 'A' &&  arg_[iLauf-2] != 'C' &&  arg_[iLauf-1] != 'T')
			   && ( arg_[iLauf-5] != 'G'  &&  arg_[iLauf-4] != 'A' &&  arg_[iLauf-3] != 'M' &&  arg_[iLauf-2] != 'M' &&  arg_[iLauf-1] != 'A')	  
			   && ( arg_[iLauf-3] != 'N'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'R' )
			   && ( arg_[iLauf-3] != 'N'  &&  arg_[iLauf-2] != 'C' &&  arg_[iLauf-1] != 'R' )
			   && ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'Q' &&  arg_[iLauf-1] != 'U' )
			   && ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'Q' &&  arg_[iLauf-1] != 'R' )
			   && ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'G' &&  arg_[iLauf-1] != 'N' )
			   && ( arg_[iLauf-3] != 'C'  &&  arg_[iLauf-2] != 'U' &&  arg_[iLauf-1] != 'R' )
			   && ( arg_[iLauf-3] != 'C'  &&  arg_[iLauf-2] != 'U' &&  arg_[iLauf-1] != 'B' )
			   && ( arg_[iLauf-3] != 'R'  &&  arg_[iLauf-2] != 'C' &&  arg_[iLauf-1] != 'P' )
			   && ( arg_[iLauf-3] != 'L'  &&  arg_[iLauf-2] != 'G' &&  arg_[iLauf-1] != 'X' )
			   && ( arg_[iLauf-3] != 'Z'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'W' )
			   && ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != 'Z' &&  arg_[iLauf-1] != 'W' )
			   && ( arg_[iLauf-3] != 'V'  &&  arg_[iLauf-2] != 'R' &&  arg_[iLauf-1] != '-' )
			   && ( arg_[iLauf-3] != 'K'  &&  arg_[iLauf-2] != 'M' &&  arg_[iLauf-1] != '-' )
			   && ( arg_[iLauf-3] != 'V'  &&  arg_[iLauf-2] != 'R' &&  arg_[iLauf-1] != 'W' )
			   && ( arg_[iLauf-3] != 'K'  &&  arg_[iLauf-2] != 'M' &&  arg_[iLauf-1] != 'W' )
			   && ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != 'R' &&  arg_[iLauf-1] != 'M' )
			   && ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'I' &&  arg_[iLauf-1] != 'N' )
			   && ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'S' &&  arg_[iLauf-1] != 'N' )
			   && ( arg_[iLauf-3] != 'C'  &&  arg_[iLauf-2] != 'O' &&  arg_[iLauf-1] != 'S' )
			   && ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'C' &&  arg_[iLauf-1] != 'S' )
			   && ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'A' &&  arg_[iLauf-1] != 'N' )
			   && ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'T' &&  arg_[iLauf-1] != 'N' )
			   && ( arg_[iLauf-3] != 'H'  &&  arg_[iLauf-2] != 'S' &&  arg_[iLauf-1] != 'N' )
			   && ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'H' &&  arg_[iLauf-1] != 'S' )
			   && ( arg_[iLauf-3] != 'H'  &&  arg_[iLauf-2] != 'C' &&  arg_[iLauf-1] != 'S' )
			   && ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'H' &&  arg_[iLauf-1] != 'C' )
			   && ( arg_[iLauf-3] != 'H'  &&  arg_[iLauf-2] != 'T' &&  arg_[iLauf-1] != 'N' )
			   && ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'H' &&  arg_[iLauf-1] != 'T' )
			   && ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'W' )
			   && ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != 'T' &&  arg_[iLauf-1] != 'W' )
			   && ( arg_[iLauf-3] != 'X'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'W' )
			   && ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != 'X' &&  arg_[iLauf-1] != 'W' )
			   && ( arg_[iLauf-3] != 'F'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'W' )
			   && ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != 'F' &&  arg_[iLauf-1] != 'W' )
			   && ( arg_[iLauf-3] != 'R'  &&  arg_[iLauf-2] != 'N' &&  arg_[iLauf-1] != 'D' )
			   && ( arg_[iLauf-3] != 'F'  &&  arg_[iLauf-2] != 'Z' &&  arg_[iLauf-1] != 'R' )
			   && ( arg_[iLauf-3] != 'R'  &&  arg_[iLauf-2] != 'F' &&  arg_[iLauf-1] != 'Z' )
			   && ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'M' &&  arg_[iLauf-1] != '_' )
			   && ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'M' &&  arg_[iLauf-1] != 'X' )
			   && ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'U' &&  arg_[iLauf-1] != 'M' )
			   && ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'D' &&  arg_[iLauf-1] != '_' )
			   && ( arg_[iLauf-3] != 'V'  &&  arg_[iLauf-2] != 'A' &&  arg_[iLauf-1] != '_' )
			   && ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'D' &&  arg_[iLauf-1] != 'G' )
			   && ( arg_[iLauf-3] != 'V'  &&  arg_[iLauf-2] != 'A' &&  arg_[iLauf-1] != 'G' )
			   && ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'M' &&  arg_[iLauf-1] != 'G' )
			   && ( arg_[iLauf-4] != 'P'  &&  arg_[iLauf-3] != 'S' &&  arg_[iLauf-2] != 'U' &&  arg_[iLauf-1] != 'M' )
			   && ( arg_[iLauf-3] != 'G'  &&  arg_[iLauf-2] != 'M' &&  arg_[iLauf-1] != '_' )
			   && ( arg_[iLauf-3] != 'H'  &&  arg_[iLauf-2] != 'M' &&  arg_[iLauf-1] != '_' )
			   && ( arg_[iLauf-3] != 'D'  &&  arg_[iLauf-2] != '_' &&  arg_[iLauf-1] != '_' )
			   && ( arg_[iLauf-3] != 'K'  &&  arg_[iLauf-2] != 'O' &&  arg_[iLauf-1] != 'R' )
			   && ( arg_[iLauf-3] != 'C'  &&  arg_[iLauf-2] != 'O' &&  arg_[iLauf-1] != 'V' )
			   && ( arg_[iLauf-3] != 'D'  &&  arg_[iLauf-2] != 'E' &&  arg_[iLauf-1] != 'T' )
			   && ( arg_[iLauf-3] != 'R'  &&  arg_[iLauf-2] != 'E' &&  arg_[iLauf-1] != 'D' )
			   && ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'Y' &&  arg_[iLauf-1] != 'X' )
			   && ( arg_[iLauf-3] != 'B'  &&  arg_[iLauf-2] != 'Y' &&  arg_[iLauf-1] != 'X' )
			   && ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'X' &&  arg_[iLauf-1] != 'Y' )
			   && ( arg_[iLauf-3] != 'B'  &&  arg_[iLauf-2] != 'X' &&  arg_[iLauf-1] != 'Y' )
			   && ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'R' &&  arg_[iLauf-1] != 'W' )
			   && ( arg_[iLauf-3] != 'Z'  &&  arg_[iLauf-2] != 'R' &&  arg_[iLauf-1] != 'R' )
			   && ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'F' &&  arg_[iLauf-1] != 'Z' )
			   && ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != 'M' &&  arg_[iLauf-1] != '_' )
			   && ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'U' &&  arg_[iLauf-1] != '_' )
			   //if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'D' &&  arg_[iLauf-1] != 'C' )
			   && ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'V' &&  arg_[iLauf-1] != '_' )
			   && ( arg_[iLauf-3] != 'E'  &&  arg_[iLauf-2] != 'D' &&  arg_[iLauf-1] != 'X' )
			   && ( arg_[iLauf-3] != 'C'  &&  arg_[iLauf-2] != 'Q' &&  arg_[iLauf-1] != 'T' )
			   && ( arg_[iLauf-3] != 'M'  &&  arg_[iLauf-2] != 'I' &&  arg_[iLauf-1] != 'N' )
			   && ( arg_[iLauf-3] != 'M'  &&  arg_[iLauf-2] != 'A' &&  arg_[iLauf-1] != 'X' )
			   && ( arg_[iLauf-3] != 'N'  &&  arg_[iLauf-2] != '_' &&  arg_[iLauf-1] != '_' )
			   && ( arg_[iLauf-3] != 'R'  &&  arg_[iLauf-2] != 'N' &&  arg_[iLauf-1] != 'G' )
			   && ( arg_[iLauf-4] != 'U'  &&  arg_[iLauf-3] != 'T' &&  arg_[iLauf-2] != 'S' &&  arg_[iLauf-1] != '_' )
			   && ( arg_[iLauf-4] != 'S'  &&  arg_[iLauf-3] != 'U' &&  arg_[iLauf-2] != 'T' &&  arg_[iLauf-1] != 'S' )
			   && ( arg_[iLauf-4] != 'M'  &&  arg_[iLauf-3] != 'U' &&  arg_[iLauf-2] != 'T' &&  arg_[iLauf-1] != 'S' )
			   && ( arg_[iLauf-4] != 'Z'  &&  arg_[iLauf-3] != 'U' &&  arg_[iLauf-2] != 'T' &&  arg_[iLauf-1] != 'S' )
			   && ( arg_[iLauf-4] != 'W'  &&  arg_[iLauf-3] != 'T' &&  arg_[iLauf-2] != 'S' &&  arg_[iLauf-1] != '_' )
			   && ( arg_[iLauf-4] != 'S'  &&  arg_[iLauf-3] != 'W' &&  arg_[iLauf-2] != 'T' &&  arg_[iLauf-1] != 'S' )
			   && ( arg_[iLauf-4] != 'M'  &&  arg_[iLauf-3] != 'W' &&  arg_[iLauf-2] != 'T' &&  arg_[iLauf-1] != 'S' )
			   && ( arg_[iLauf-4] != 'Z'  &&  arg_[iLauf-3] != 'W' &&  arg_[iLauf-2] != 'T' &&  arg_[iLauf-1] != 'S' )
			   && ( arg_[iLauf-4] != 'R'  &&  arg_[iLauf-3] != 'S' &&  arg_[iLauf-2] != 'U' &&  arg_[iLauf-1] != 'M' )
			   && ( arg_[iLauf-4] != 'X'  &&  arg_[iLauf-3] != 'S' &&  arg_[iLauf-2] != 'U' &&  arg_[iLauf-1] != 'M' )
			   && ( arg_[iLauf-4] != 'Q'  &&  arg_[iLauf-3] != 'S' &&  arg_[iLauf-2] != 'U' &&  arg_[iLauf-1] != 'M' )
			   && ( arg_[iLauf-3] != 'M'  &&  arg_[iLauf-2] != 'R' &&  arg_[iLauf-1] != '_' )
			   && ( arg_[iLauf-3] != 'K'  &&  arg_[iLauf-2] != 'R' &&  arg_[iLauf-1] != 'S' )
			   && ( arg_[iLauf-3] != 'R'  &&  arg_[iLauf-2] != 'D' &&  arg_[iLauf-1] != 'N' )
			   && ( arg_[iLauf-3] != 'M'  &&  arg_[iLauf-2] != 'D' &&  arg_[iLauf-1] != '_' )
			   && ( arg_[iLauf-3] != 'V'  &&  arg_[iLauf-2] != 'F' &&  arg_[iLauf-1] != 'X' )
			   && ( arg_[iLauf-3] != 'M'  &&  arg_[iLauf-2] != 'N' &&  arg_[iLauf-1] != 'X' )
			   && ( arg_[iLauf-4] != 'V'  &&  arg_[iLauf-3] != 'F' &&  arg_[iLauf-2] != 'Y' &&  arg_[iLauf-1] != 'X' )
			   && ( arg_[iLauf-4] != 'M'  &&  arg_[iLauf-3] != 'N' &&  arg_[iLauf-2] != 'Y' &&  arg_[iLauf-1] != 'X' )
			   && ( arg_[iLauf-3] != 'K'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'H' )
			   && ( arg_[iLauf-3] != 'K'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'M' )
			   && ( arg_[iLauf-3] != 'X'  &&  arg_[iLauf-2] != 'K' &&  arg_[iLauf-1] != 'P' )
			   && ( arg_[iLauf-4] != 'K'  &&  arg_[iLauf-3] != 'T' &&  arg_[iLauf-2] != 'E' &&  arg_[iLauf-1] != 'T' )
			   && ( arg_[iLauf-3] != 'R'  &&  arg_[iLauf-2] != 'A' &&  arg_[iLauf-1] != 'D' )
			   && ( arg_[iLauf-3] != 'D'  &&  arg_[iLauf-2] != 'E' &&  arg_[iLauf-1] != 'G' )
			   && ( arg_[iLauf-4] != 'G'  &&  arg_[iLauf-3] != 'R' &&  arg_[iLauf-2] != 'A' &&  arg_[iLauf-1] != 'D' )
			   && ( arg_[iLauf-3] != 'D'  &&  arg_[iLauf-2] != 'G' &&  arg_[iLauf-1] != 'R' )
			   && ( arg_[iLauf-3] != 'C'  &&  arg_[iLauf-2] != 'O' &&  arg_[iLauf-1] != 'T' )
			   && ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'E' &&  arg_[iLauf-1] != 'C' )
			   && ( arg_[iLauf-3] != 'C'  &&  arg_[iLauf-2] != 'S' &&  arg_[iLauf-1] != 'E' )
			   && ( arg_[iLauf-3] != 'H'  &&  arg_[iLauf-2] != 'C' &&  arg_[iLauf-1] != 'T' )
			   && ( arg_[iLauf-3] != 'H'  &&  arg_[iLauf-2] != 'S' &&  arg_[iLauf-1] != 'E' )
			   && ( arg_[iLauf-3] != 'H'  &&  arg_[iLauf-2] != 'C' &&  arg_[iLauf-1] != 'E' )
			   && ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'C' &&  arg_[iLauf-1] != 'T' )
			   && ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'S' &&  arg_[iLauf-1] != 'E' )
			   && ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'C' &&  arg_[iLauf-1] != 'E' )
		       && ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'H' &&  arg_[iLauf-1] != 'G' )
			   && ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'H' &&  arg_[iLauf-1] != 'N' )
			   && ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'H' &&  arg_[iLauf-1] != 'O' )
			   && ( arg_[iLauf-3] != 'D'  &&  arg_[iLauf-2] != 'Z' &&  arg_[iLauf-1] != 'W' )
			   && ( arg_[iLauf-4] != 'S'  &&  arg_[iLauf-3] != 'T' &&  arg_[iLauf-2] != 'E' &&  arg_[iLauf-1] != 'T' )
			   && ( arg_[iLauf-4] != 'Z'  &&  arg_[iLauf-3] != 'T' &&  arg_[iLauf-2] != 'E' &&  arg_[iLauf-1] != 'T' )
			   && ( arg_[iLauf-3] != 'K'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'B' )
			   && ( arg_[iLauf-3] != 'K'  &&  arg_[iLauf-2] != 'B' &&  arg_[iLauf-1] != 'S' )
			   && ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'B' &&  arg_[iLauf-1] != 'S' )
		       && ( arg_[iLauf-3] != 'Z'  &&  arg_[iLauf-2] != 'B' &&  arg_[iLauf-1] != 'S' )
			   && ( arg_[iLauf-3] != 'B'  &&  arg_[iLauf-2] != 'S' &&  arg_[iLauf-1] != 'K' )
			   && ( arg_[iLauf-3] != 'K'  &&  arg_[iLauf-2] != 'B' &&  arg_[iLauf-1] != 'R' )
			   && ( arg_[iLauf-3] != 'Z'  &&  arg_[iLauf-2] != 'B' &&  arg_[iLauf-1] != 'R' )
			   && ( arg_[iLauf-1] != ';' )
			   && ( arg_[iLauf-3] != 'B'  &&  arg_[iLauf-2] != 'N' &&  arg_[iLauf-1] != 'W' )
			   && ( arg_[iLauf-3] != 'B'  &&  arg_[iLauf-2] != 'N' &&  arg_[iLauf-1] != 'P' )
			   && ( arg_[iLauf-3] != 'M'  &&  arg_[iLauf-2] != 'N' &&  arg_[iLauf-1] != 'P' )
			   && ( arg_[iLauf-3] != 'N'  &&  arg_[iLauf-2] != 'B' &&  arg_[iLauf-1] != 'W' )
			   && ( arg_[iLauf-3] != 'H'  &&  arg_[iLauf-2] != 'G' &&  arg_[iLauf-1] != 'W' )
			   && ( arg_[iLauf-3] != 'H'  &&  arg_[iLauf-2] != 'G' &&  arg_[iLauf-1] != 'P' )
			   && ( arg_[iLauf-3] != 'G'  &&  arg_[iLauf-2] != 'M' &&  arg_[iLauf-1] != 'W' )
			   && ( arg_[iLauf-3] != 'G'  &&  arg_[iLauf-2] != 'M' &&  arg_[iLauf-1] != 'P' )
			   && ( arg_[iLauf-3] != 'N'  &&  arg_[iLauf-2] != 'B' &&  arg_[iLauf-1] != 'P' )
			   && ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != 'N' &&  arg_[iLauf-1] != 'W' )
			   && ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != 'N' &&  arg_[iLauf-1] != 'P' )
			   && ( arg_[iLauf-3] != 'Z'  &&  arg_[iLauf-2] != 'D' &&  arg_[iLauf-1] != 'W' )
			   && ( arg_[iLauf-4] != 'F'  &&  arg_[iLauf-3] != 'O' &&  arg_[iLauf-2] != 'R' &&  arg_[iLauf-1] != 'M' )
			   && ( arg_[iLauf-4] != 'A'  &&  arg_[iLauf-3] != 'G' &&  arg_[iLauf-2] != 'A' &&  arg_[iLauf-1] != 'M' )
		       && ( arg_[iLauf-4] != 'B'  &&  arg_[iLauf-3] != 'G' &&  arg_[iLauf-2] != 'A' &&  arg_[iLauf-1] != 'M' )
			   && ( arg_[iLauf-4] != 'D'  &&  arg_[iLauf-3] != 'G' &&  arg_[iLauf-2] != 'A' &&  arg_[iLauf-1] != 'M' )
			   && ( arg_[iLauf-3] != 'R'  &&  arg_[iLauf-2] != 'D' &&  arg_[iLauf-1] != 'A' )   
			   && ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != 'Z' &&  arg_[iLauf-1] != 'D' ) 
			   && ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'M' &&  arg_[iLauf-1] != 'G' ) 
			   && ( arg_[iLauf-3] != 'E'  &&  arg_[iLauf-2] != 'X' &&  arg_[iLauf-1] != 'P' )
			   && ( arg_[iLauf-3] != 'G'  &&  arg_[iLauf-2] != 'F' &&  arg_[iLauf-1] != 'Z' ) 
			   && ( arg_[iLauf-3] != 'D'  &&  arg_[iLauf-2] != 'T' &&  arg_[iLauf-1] != 'W' )
			   && ( arg_[iLauf-3] != 'D'  &&  arg_[iLauf-2] != 'X' &&  arg_[iLauf-1] != 'W' )
			   && ( arg_[iLauf-3] != 'D'  &&  arg_[iLauf-2] != 'F' &&  arg_[iLauf-1] != 'W' ) 
			   && ( arg_[iLauf-3] != 'F'  &&  arg_[iLauf-2] != 'M' &&  arg_[iLauf-1] != 'K' ) 
			   && ( arg_[iLauf-3] != 'F'  &&  arg_[iLauf-2] != 'M' &&  arg_[iLauf-1] != 'P' ) 
			   && ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'U' &&  arg_[iLauf-1] != 'X' ) 
			   && ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'T' &&  arg_[iLauf-1] != '_' ) 

			   && ( arg_[iLauf-3] != 'M'  &&  arg_[iLauf-2] != 'R' &&  arg_[iLauf-1] != 'I' ) 
			   && ( arg_[iLauf-4] != 'P'  &&  arg_[iLauf-3] != 'K' &&  arg_[iLauf-2] != 'R' &&  arg_[iLauf-1] != 'B' )
			   && ( arg_[iLauf-4] != 'P'  &&  arg_[iLauf-3] != 'K' &&  arg_[iLauf-2] != 'S' &&  arg_[iLauf-1] != 'B' )
						   
			   && ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != 'K' && (arg_[iLauf-1] != 'R' 
				                                                   ||  arg_[iLauf-1] != 'S' ))
			   && ( arg_[iLauf-3] != 'M'  &&  arg_[iLauf-2] != 'K' &&  arg_[iLauf-1] != 'R' )
			   && ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'B' &&  arg_[iLauf-1] != 'M' )
			   && ( arg_[iLauf-4] != 'M'  &&  arg_[iLauf-3] != 'K' &&  arg_[iLauf-2] != 'R' &&  arg_[iLauf-1] != 'N' )
			   && ( arg_[iLauf-3] != 'B'  &&  arg_[iLauf-2] != 'M' &&  arg_[iLauf-1] != 'K' )
			   && ( arg_[iLauf-3] != 'M'  &&  arg_[iLauf-2] != 'B' &&  arg_[iLauf-1] != 'C' ) 
			   && ( arg_[iLauf-3] != 'M'  &&  arg_[iLauf-2] != 'X' && (arg_[iLauf-1] != 'A' 
				                                                   ||  arg_[iLauf-1] != 'S'
																   ||  arg_[iLauf-1] != 'I'
																   ||  arg_[iLauf-1] != 'V'
																   ||  arg_[iLauf-1] != 'M'
				                                                   ||  arg_[iLauf-1] != 'T' ))
			   
			   && ( arg_[iLauf-3] != 'M'  &&  arg_[iLauf-2] != 'S' &&  arg_[iLauf-1] != 'P' ) 
			   && ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'K' &&  arg_[iLauf-1] != 'M' ) 
			   && ( arg_[iLauf-3] != 'Z'  &&  arg_[iLauf-2] != 'K' &&  arg_[iLauf-1] != 'R' ) 
				   
			   && ( arg_[iLauf-3] != 'M'  &&  arg_[iLauf-2] != 'A' &&  arg_[iLauf-1] != 'C' ) 
			   && ( arg_[iLauf-3] != 'M'  &&  arg_[iLauf-2] != 'D' &&  arg_[iLauf-1] != 'T' )
			   
			   && ( arg_[iLauf-3] != 'F'  &&  arg_[iLauf-2] != 'X' && (arg_[iLauf-1] != '0' 
				   	                                               ||  arg_[iLauf-1] != '1' 
																   ||  arg_[iLauf-1] != '2' ))
			   && ( arg_[iLauf-4] != 'I'  &&  arg_[iLauf-3] != 'A' &&  arg_[iLauf-2] != 'C' && (arg_[iLauf-1] != 'T' 
																							||  arg_[iLauf-1] != 'E' ))
			   && ( arg_[iLauf-4] != 'I'  &&  arg_[iLauf-3] != 'A' &&  arg_[iLauf-2] != 'S' &&  arg_[iLauf-1] != 'E' )
			   && ( arg_[iLauf-4] != 'I'  &&  arg_[iLauf-3] != 'A' &&  arg_[iLauf-2] != 'H' && (arg_[iLauf-1] != 'S'  
																							||  arg_[iLauf-1] != 'C' 
																							||  arg_[iLauf-1] != 'T' 
																							||  arg_[iLauf-1] != 'G' 
																							||  arg_[iLauf-1] != 'N' 
																							||  arg_[iLauf-1] != 'O' ))
				&& ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'I' &&  arg_[iLauf-1] != 'G' ) 
				&& ( arg_[iLauf-3] != 'M'  &&  arg_[iLauf-2] != 'X' &&  arg_[iLauf-1] != 'Q' ) 
				&& ( arg_[iLauf-3] != 'V'  &&  arg_[iLauf-2] != 'A' &&  arg_[iLauf-1] != 'X' )
				&& ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'M' &&  arg_[iLauf-1] != 'G' )
				&& ( arg_[iLauf-3] != 'C'  &&  arg_[iLauf-2] != 'O' &&  arg_[iLauf-1] != 'X' )
				&& ( arg_[iLauf-3] != 'K'  &&  arg_[iLauf-2] != 'O' &&  arg_[iLauf-1] != 'X' )
				&& ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'D' &&  arg_[iLauf-1] != 'X' )
				&& ( arg_[iLauf-3] != 'G'  &&  arg_[iLauf-2] != 'S' &&  arg_[iLauf-1] != 'D' )
				&& ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != 'I' &&  arg_[iLauf-1] != '_' )
				&& ( arg_[iLauf-3] != 'E'  &&  arg_[iLauf-2] != 'U' &&  arg_[iLauf-1] != 'L' )
			    && ( arg_[iLauf-3] != 'C'  &&  arg_[iLauf-2] != 'I' &&  arg_[iLauf-1] != '_' )
				&& ( arg_[iLauf-3] != 'E'  &&  arg_[iLauf-2] != 'F' &&  arg_[iLauf-1] != 'G' )
				&& ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'N' &&  arg_[iLauf-1] != 'I' )
				&& ( arg_[iLauf-3] != 'B'  &&  arg_[iLauf-2] != 'N' &&  arg_[iLauf-1] != 'I' )
				&& ( arg_[iLauf-3] != 'X'  &&  arg_[iLauf-2] != 'C' &&  arg_[iLauf-1] != 'A' )
				&& ( arg_[iLauf-3] != 'X'  &&  arg_[iLauf-2] != 'C' &&  arg_[iLauf-1] != 'B' )
				&& ( arg_[iLauf-3] != 'I'  &&  arg_[iLauf-2] != 'M' &&  arg_[iLauf-1] != 'B' )
				&& ( arg_[iLauf-3] != 'O'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'N' )
			    && ( arg_[iLauf-3] != 'E'  &&  arg_[iLauf-2] != 'F' &&  arg_[iLauf-1] != 'S' )
				&& ( arg_[iLauf-3] != 'O'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'P' )
			    && ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'W' &&  arg_[iLauf-1] != 'X' )
				
				&& ( arg_[iLauf-3] != 'B'  &&  arg_[iLauf-2] != 'N' &&  arg_[iLauf-1] != '0' )
				&& ( arg_[iLauf-3] != 'B'  &&  arg_[iLauf-2] != 'N' &&  arg_[iLauf-1] != '1' )
			    && ( arg_[iLauf-3] != 'B'  &&  arg_[iLauf-2] != 'N' &&  arg_[iLauf-1] != '2' )
				&& ( arg_[iLauf-3] != '!'  &&  arg_[iLauf-2] != '.' &&  arg_[iLauf-1] != '!' )

				&& ( arg_[iLauf-3] != 'H'  &&  arg_[iLauf-2] != 'G' &&  arg_[iLauf-1] != '0' )
				&& ( arg_[iLauf-3] != 'H'  &&  arg_[iLauf-2] != 'G' &&  arg_[iLauf-1] != '1' )
				&& ( arg_[iLauf-3] != 'Z'  &&  arg_[iLauf-2] != 'H' &&  arg_[iLauf-1] != 'G' )
				&& ( arg_[iLauf-3] != 'Z'  &&  arg_[iLauf-2] != 'B' &&  arg_[iLauf-1] != 'N' )
				&& ( arg_[iLauf-3] != 'Z'  &&  arg_[iLauf-2] != 'F' &&  arg_[iLauf-1] != 'X' )
				&& ( arg_[iLauf-3] != 'H'  &&  arg_[iLauf-2] != 'G' &&  arg_[iLauf-1] != '2' )
				&& ( arg_[iLauf-3] != 'R'  &&  arg_[iLauf-2] != 'N' &&  arg_[iLauf-1] != 'V' )
				&& ( arg_[iLauf-3] != 'K'  &&  arg_[iLauf-2] != 'L' &&  arg_[iLauf-1] != 'X' )
				&& ( arg_[iLauf-3] != 'K'  &&  arg_[iLauf-2] != 'F' &&  arg_[iLauf-1] != 'A' )
				)if ( arg_[iLauf-3] != 'K'  &&  arg_[iLauf-2] != 'L' &&  arg_[iLauf-1] != '0' )
				if ( arg_[iLauf-3] != 'K'  &&  arg_[iLauf-2] != 'L' &&  arg_[iLauf-1] != '2' )
				if ( arg_[iLauf-3] != 'M'  &&  arg_[iLauf-2] != 'N' &&  arg_[iLauf-1] != '0' )
				if ( arg_[iLauf-3] != 'M'  &&  arg_[iLauf-2] != 'N' &&  arg_[iLauf-1] != '2' )
				if ( arg_[iLauf-3] != 'X'  &&  arg_[iLauf-2] != 'H' &&  arg_[iLauf-1] != 'F' )
				if ( arg_[iLauf-3] != 'H'  &&  arg_[iLauf-2] != 'F' &&  arg_[iLauf-1] != '0' )
				if ( arg_[iLauf-3] != 'H'  &&  arg_[iLauf-2] != 'F' &&  arg_[iLauf-1] != '2' )
				if ( arg_[iLauf-3] != 'C'  &&  arg_[iLauf-2] != 'H' &&  arg_[iLauf-1] != 'F' )
				if ( arg_[iLauf-3] != 'C'  &&  arg_[iLauf-2] != 'K' &&  arg_[iLauf-1] != 'L' )
				if ( arg_[iLauf-3] != 'C'  &&  arg_[iLauf-2] != 'H' &&  arg_[iLauf-1] != 'G' )
				if ( arg_[iLauf-3] != 'M'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'W' )
				if ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'A' &&  arg_[iLauf-1] != 'A' )
				if ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'E' &&  arg_[iLauf-1] != 'U' )
				if ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'W' &&  arg_[iLauf-1] != 'N' )
				if ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'E' &&  arg_[iLauf-1] != 'A' )
				if ( arg_[iLauf-3] != 'B'  &&  arg_[iLauf-2] != 'W' &&  arg_[iLauf-1] != 'A' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'W' &&  arg_[iLauf-1] != 'A' )
				if ( arg_[iLauf-3] != 'B'  &&  arg_[iLauf-2] != 'Y' &&  arg_[iLauf-1] != 'S' )
				if ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'D' &&  arg_[iLauf-1] != 'V' )
				if ( arg_[iLauf-3] != 'L'  &&  arg_[iLauf-2] != 'T' &&  arg_[iLauf-1] != 'O' )
				if ( arg_[iLauf-3] != 'K'  &&  arg_[iLauf-2] != '_' &&  arg_[iLauf-1] != 'M' )
				if ( arg_[iLauf-3] != 'K'  &&  arg_[iLauf-2] != 'W' &&  arg_[iLauf-1] != 'M' )
				if ( arg_[iLauf-3] != 'V'  &&  arg_[iLauf-2] != '_' &&  arg_[iLauf-1] != 'M' )
				if ( arg_[iLauf-3] != 'V'  &&  arg_[iLauf-2] != 'W' &&  arg_[iLauf-1] != 'M' )
				if ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != '2' &&  arg_[iLauf-1] != 'M' )
				if ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != '_' &&  arg_[iLauf-1] != 'M' )
				if ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != 'M' &&  arg_[iLauf-1] != 'M' )
				if ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != 'M' &&  arg_[iLauf-1] != 'W' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'B' &&  arg_[iLauf-1] != 'Z' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'Z' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != '1' &&  arg_[iLauf-1] != 'Z' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != '2' &&  arg_[iLauf-1] != 'Z' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'D' &&  arg_[iLauf-1] != 'Z' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'B' &&  arg_[iLauf-1] != 'T' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'T' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != '1' &&  arg_[iLauf-1] != 'T' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != '2' &&  arg_[iLauf-1] != 'T' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'D' &&  arg_[iLauf-1] != 'T' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'B' &&  arg_[iLauf-1] != 'X' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'X' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != '1' &&  arg_[iLauf-1] != 'X' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != '2' &&  arg_[iLauf-1] != 'X' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'D' &&  arg_[iLauf-1] != 'X' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'B' &&  arg_[iLauf-1] != 'F' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'F' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != '1' &&  arg_[iLauf-1] != 'F' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != '2' &&  arg_[iLauf-1] != 'F' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'D' &&  arg_[iLauf-1] != 'F' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'B' &&  arg_[iLauf-1] != 'B' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'W' &&  arg_[iLauf-1] != 'B' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != '1' &&  arg_[iLauf-1] != 'B' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != '2' &&  arg_[iLauf-1] != 'B' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'B' &&  arg_[iLauf-1] != 'H' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'W' &&  arg_[iLauf-1] != 'H' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != '1' &&  arg_[iLauf-1] != 'H' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != '2' &&  arg_[iLauf-1] != 'H' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'C' &&  arg_[iLauf-1] != 'H' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'B' &&  arg_[iLauf-1] != 'R' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'K' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != '1' &&  arg_[iLauf-1] != 'K' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != '2' &&  arg_[iLauf-1] != 'K' )
				if ( arg_[iLauf-3] != 'B'  &&  arg_[iLauf-2] != 'N' &&  arg_[iLauf-1] != 'M' )
				if ( arg_[iLauf-3] != 'B'  &&  arg_[iLauf-2] != 'N' &&  arg_[iLauf-1] != 'S' )
				if ( arg_[iLauf-3] != 'H'  &&  arg_[iLauf-2] != 'G' &&  arg_[iLauf-1] != 'M' )
				if ( arg_[iLauf-3] != 'H'  &&  arg_[iLauf-2] != 'G' &&  arg_[iLauf-1] != 'S' )
				if ( arg_[iLauf-3] != 'R'  &&  arg_[iLauf-2] != 'Y' &&  arg_[iLauf-1] != 'X' )
				if ( arg_[iLauf-3] != 'G'  &&  arg_[iLauf-2] != 'V' &&  arg_[iLauf-1] != 'A' )
				if ( arg_[iLauf-3] != 'G'  &&  arg_[iLauf-2] != 'S' &&  arg_[iLauf-1] != 'M' )
				if ( arg_[iLauf-3] != 'Z'  &&  arg_[iLauf-2] != '_' &&  arg_[iLauf-1] != 'W' )
				if ( arg_[iLauf-3] != 'Z'  &&  arg_[iLauf-2] != '_' &&  arg_[iLauf-1] != '_' )
				if ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'C' &&  arg_[iLauf-1] != 'H' )
				if ( arg_[iLauf-3] != 'E'  &&  arg_[iLauf-2] != 'X' &&  arg_[iLauf-1] != 'Z' )
				if ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'S' &&  arg_[iLauf-1] != 'H' )
				if ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'E' &&  arg_[iLauf-1] != 'X' )
				if ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'W' &&  arg_[iLauf-1] != '_' )
				if ( arg_[iLauf-3] != 'I'  &&  arg_[iLauf-2] != 'Q' &&  arg_[iLauf-1] != 'K' )
				if ( arg_[iLauf-3] != 'I'  &&  arg_[iLauf-2] != 'Q' &&  arg_[iLauf-1] != '_' )
				if ( arg_[iLauf-3] != 'C'  &&  arg_[iLauf-2] != 'W' &&  arg_[iLauf-1] != '_' )
				if ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'T' &&  arg_[iLauf-1] != 'N' )
				if ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'N' &&  arg_[iLauf-1] != '_' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != '_' &&  arg_[iLauf-1] != '_' )
				if ( arg_[iLauf-3] != 'Z'  &&  arg_[iLauf-2] != 'S' &&  arg_[iLauf-1] != 'H' )
				if ( arg_[iLauf-3] != 'Z'  &&  arg_[iLauf-2] != 'E' &&  arg_[iLauf-1] != 'X' )
				if ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != '_' &&  arg_[iLauf-1] != '_' )
				if ( arg_[iLauf-3] != 'W'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != '_' )
				if ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != 'R' &&  arg_[iLauf-1] != '_' )
				if ( arg_[iLauf-3] != 'Z'  &&  arg_[iLauf-2] != '_' &&  arg_[iLauf-1] != 'P' )
				if ( arg_[iLauf-3] != 'S'  &&  arg_[iLauf-2] != 'H' &&  arg_[iLauf-1] != 'P' )
				if ( arg_[iLauf-3] != 'E'  &&  arg_[iLauf-2] != 'Z' &&  arg_[iLauf-1] != 'P' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'F' &&  arg_[iLauf-1] != 'S' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'T' &&  arg_[iLauf-1] != 'S' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'X' &&  arg_[iLauf-1] != 'S' )
				if ( arg_[iLauf-3] != 'M'  &&  arg_[iLauf-2] != 'K' &&  arg_[iLauf-1] != 'P' )
				if ( arg_[iLauf-3] != 'R'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'T' )
				if ( arg_[iLauf-3] != 'R'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'Z' )
				if ( arg_[iLauf-3] != 'K'  &&  arg_[iLauf-2] != 'R' &&  arg_[iLauf-1] != 'P' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'R' &&  arg_[iLauf-1] != 'S' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'Z' &&  arg_[iLauf-1] != 'S' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'M' &&  arg_[iLauf-1] != 'S' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'S' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'E' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'N' &&  arg_[iLauf-1] != 'E' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'E' &&  arg_[iLauf-1] != 'E' )
				if ( arg_[iLauf-3] != 'O'  &&  arg_[iLauf-2] != 'N' &&  arg_[iLauf-1] != 'Z' )
				if ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != 'T' &&  arg_[iLauf-1] != 'D' )
				if ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != 'X' &&  arg_[iLauf-1] != 'D' )
				if ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != 'F' &&  arg_[iLauf-1] != 'D' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'K' &&  arg_[iLauf-1] != 'V' )
				if ( arg_[iLauf-2] != 'V'  &&  arg_[iLauf-1] != '_' )
				if ( arg_[iLauf-3] != 'R'  &&  arg_[iLauf-2] != 'N' &&  arg_[iLauf-1] != 'N' )
				if ( arg_[iLauf-3] != 'L'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'W' )
				if ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != 'L' &&  arg_[iLauf-1] != 'W' )
				if ( arg_[iLauf-3] != 'D'  &&  arg_[iLauf-2] != 'L' &&  arg_[iLauf-1] != 'W' )
				if ( arg_[iLauf-3] != 'B'  &&  arg_[iLauf-2] != 'S' &&  arg_[iLauf-1] != 'M' )
				if ( arg_[iLauf-3] != 'H'  &&  arg_[iLauf-2] != 'S' &&  arg_[iLauf-1] != 'M' )
				if ( arg_[iLauf-3] != 'R'  &&  arg_[iLauf-2] != 'L' &&  arg_[iLauf-1] != 'T' )
				if ( arg_[iLauf-3] != 'U'  &&  arg_[iLauf-2] != 'V' &&  arg_[iLauf-1] != 'S' )
				if ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'X' )
				if ( arg_[iLauf-3] != 'A'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'W' )
				if ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != 'A' &&  arg_[iLauf-1] != 'W' )
				if ( arg_[iLauf-3] != 'D'  &&  arg_[iLauf-2] != 'A' &&  arg_[iLauf-1] != 'W' )
				if ( arg_[iLauf-3] != 'V'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'W' )
				if ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != 'V' &&  arg_[iLauf-1] != 'W' )
				if ( arg_[iLauf-3] != 'D'  &&  arg_[iLauf-2] != 'V' &&  arg_[iLauf-1] != 'W' )
				if ( arg_[iLauf-3] != 'C'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'W' )
				if ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != 'C' &&  arg_[iLauf-1] != 'W' )
				if ( arg_[iLauf-3] != 'D'  &&  arg_[iLauf-2] != 'C' &&  arg_[iLauf-1] != 'W' )
				if ( arg_[iLauf-3] != 'W'  &&  arg_[iLauf-2] != 'P' &&  arg_[iLauf-1] != 'W' )
				if ( arg_[iLauf-3] != 'P'  &&  arg_[iLauf-2] != 'W' &&  arg_[iLauf-1] != 'W' )
				if ( arg_[iLauf-3] != 'D'  &&  arg_[iLauf-2] != 'W' &&  arg_[iLauf-1] != 'W' )
				if ( arg_[iLauf-3] != 'D'  &&  arg_[iLauf-2] != 'G' &&  arg_[iLauf-1] != 'M' )
				if ( arg_[iLauf-3] != 'I'  &&  arg_[iLauf-2] != 'G' &&  arg_[iLauf-1] != 'M' )
				if ( arg_[iLauf-3] != 'F'  &&  arg_[iLauf-2] != 'D' &&  arg_[iLauf-1] != '_' )
				if ( arg_[iLauf-3] != 'I'  &&  arg_[iLauf-2] != 'F' &&  arg_[iLauf-1] != '_' )
				if ( arg_[iLauf-3] != 'G'  &&  arg_[iLauf-2] != 'F' &&  arg_[iLauf-1] != 'V' )
				if ( arg_[iLauf-3] != 'Z'  &&  arg_[iLauf-2] != 'F' &&  arg_[iLauf-1] != 'V' )
				if ( arg_[iLauf-3] != 'T'  &&  arg_[iLauf-2] != 'F' &&  arg_[iLauf-1] != 'V' )
				if ( arg_[iLauf-3] != 'X'  &&  arg_[iLauf-2] != 'F' &&  arg_[iLauf-1] != 'V' )
				if ( arg_[iLauf-3] != 'F'  &&  arg_[iLauf-2] != 'F' &&  arg_[iLauf-1] != 'V' )
				if ( arg_[iLauf-3] != 'B'  &&  arg_[iLauf-2] != 'F' &&  arg_[iLauf-1] != 'V' )
				if ( arg_[iLauf-3] != 'L'  &&  arg_[iLauf-2] != 'Z' &&  arg_[iLauf-1] != 'V' )
				if ( arg_[iLauf-3] != 'K'  &&  arg_[iLauf-2] != 'G' &&  arg_[iLauf-1] != 'L' )			   // :
				if ( arg_[iLauf-3] != 'I'  &&  arg_[iLauf-2] != 'I' &&  arg_[iLauf-1] != 'G' )			   // :
					
					
			   // :
			   // Funktionsdeklaration  //  4/4


				if ( arg_[iLauf-1] != ',' )
				 if ( arg_[iLauf-1] != '(' ) {printf("bad formula 'x('\n"); exit(0);}

	if(iLauf < laenge && arg_[iLauf] == ')' ) 
		if ( arg_[iLauf+1] != '+' )  
		 if ( arg_[iLauf+1] != '-' )
		  if ( arg_[iLauf+1] != '*' ) 
		   if ( arg_[iLauf+1] != '/' ) 
			if ( arg_[iLauf+1] != '%' ) 
			 if ( arg_[iLauf+1] != 'h' ) 
			  if ( arg_[iLauf+1] != 'v' )
			   if ( arg_[iLauf+1] != ',' )
				if ( arg_[iLauf+1] != ')' ) {printf("bad formula ')x'\n"); exit(0);}

	//-------------------------------------------------------------------------------------------> komma prüfung	
	if(arg_[iLauf] == ',' && arg_[iLauf+1] == ',') {printf("bad formula ',,'\n"); exit(0);}

	if(arg_[iLauf] == ',')
	 if(arg_[iLauf-1] != '1')
	  if(arg_[iLauf-1] != '2')
	   if(arg_[iLauf-1] != '3')
		if(arg_[iLauf-1] != '4')
		 if(arg_[iLauf-1] != '5')
		  if(arg_[iLauf-1] != '6')
		   if(arg_[iLauf-1] != '7')
			if(arg_[iLauf-1] != '8')
			 if(arg_[iLauf-1] != '9')
			  if(arg_[iLauf-1] != '0')
			   if(arg_[iLauf-1] != ')')
				if(arg_[iLauf-1] != 'a') if(arg_[iLauf-1] != 'b') if(arg_[iLauf-1] != 'c') 
				 if(arg_[iLauf-1] != 'd')  if(arg_[iLauf-1] != 'e') if(arg_[iLauf-1] != 'f') if(arg_[iLauf-1] != 'g')
				  if(arg_[iLauf-1] != 'h')  if(arg_[iLauf-1] != 'i') if(arg_[iLauf-1] != 'j') if(arg_[iLauf-1] != 'k')
				   if(arg_[iLauf-1] != 'l')  if(arg_[iLauf-1] != 'm') if(arg_[iLauf-1] != 'n') if(arg_[iLauf-1] != 'o')
					if(arg_[iLauf-1] != 'p')  if(arg_[iLauf-1] != 'q') if(arg_[iLauf-1] != 'r') if(arg_[iLauf-1] != 's')
					 if(arg_[iLauf-1] != 't')  if(arg_[iLauf-1] != 'u') if(arg_[iLauf-1] != 'v') if(arg_[iLauf-1] != 'w')
					  if(arg_[iLauf-1] != 'x')  if(arg_[iLauf-1] != 'y') if(arg_[iLauf-1] != 'z') if(arg_[iLauf-1] != '#')
						 
					  {printf("bad formula 'x,'\n"); exit(0);}

		
		if(arg_[iLauf] == ',')
		 if(arg_[iLauf+1] != '1')
		  if(arg_[iLauf+1] != '2')
		   if(arg_[iLauf+1] != '3')
			if(arg_[iLauf+1] != '4')
			 if(arg_[iLauf+1] != '5')
			  if(arg_[iLauf+1] != '6')
			   if(arg_[iLauf+1] != '7')
				if(arg_[iLauf+1] != '8')
				 if(arg_[iLauf+1] != '9')
				  if(arg_[iLauf+1] != '0')
				   if(arg_[iLauf+1] != 'a') if(arg_[iLauf+1] != 'b') if(arg_[iLauf+1] != 'c') if(arg_[iLauf+1] != '-')
					if(arg_[iLauf+1] != 'd')  if(arg_[iLauf+1] != 'e') if(arg_[iLauf+1] != 'f') if(arg_[iLauf+1] != 'g')
					 if(arg_[iLauf+1] != 'h')  if(arg_[iLauf+1] != 'i') if(arg_[iLauf+1] != 'j') if(arg_[iLauf+1] != 'k')
					  if(arg_[iLauf+1] != 'l')  if(arg_[iLauf+1] != 'm') if(arg_[iLauf+1] != 'n') if(arg_[iLauf+1] != 'o')
					   if(arg_[iLauf+1] != 'p')  if(arg_[iLauf+1] != 'q') if(arg_[iLauf+1] != 'r') if(arg_[iLauf+1] != 's')
						if(arg_[iLauf+1] != 't')  if(arg_[iLauf+1] != 'u') if(arg_[iLauf+1] != 'v') if(arg_[iLauf+1] != 'w')
						 if(arg_[iLauf+1] != 'x')  if(arg_[iLauf+1] != 'y') if(arg_[iLauf+1] != 'z') if(arg_[iLauf+1] != '(')
			 
						 {printf("bad formula ',x'\n"); exit(0);}		
}


